Commandes Générales
HisteriaMC/histeria-wiki pull request #11
Opened 2023-03-14 17:01 UTC by CercleTour

Ajout de toutes les commandes (normalement) dans un nouveau fichier general-commands.md

2023-03-14 17:13 UTC, dadodasyra requested changes

2023-03-14 17:13 UTC, dadodasyra commented on commands/general-commands.md
> +# Les commandes faction
```suggestion
# Les commandes en faction
```
```suggestion
# Les commandes en serveur faction
```

2023-03-14 17:13 UTC, dadodasyra commented on commands/general-commands.md
> +|arene|Permet de se téléporter en arène 1|
Toutes les descriptions doivent être directe. "Permet" est redondant et inutile, par exemple. 
On doit par ailleurs aussi remplacer "Description" par Description/Utilité dans la colonne (sur les 3 tableaux)
```suggestion
|arene|Se téléporter en arène 1|
```

2023-03-14 17:13 UTC, dadodasyra commented on commands/general-commands.md
> +|warp [nom]|affiche les warp disponible ou permet de se tp au warp indiqué|
Majuscule

2023-03-14 17:13 UTC, dadodasyra commented on commands/general-commands.md
> +|warp [nom]|affiche les warp disponible ou permet de se tp au warp indiqué|
```suggestion
|warp [nom]|Affiche les warp disponible ou permet de se tp au warp indiqué|
```

2023-03-14 17:13 UTC, dadodasyra commented on commands/general-commands.md
> +|vote|Vote sur le serveur et vous donne des récompenses|
Vérifie le vote, il ne permet pas de voter en lui même

2023-03-14 17:13 UTC, dadodasyra commented on commands/general-commands.md
> +|tpahere <player>|Envoie une demande pour tp un joueur sur soi.|
```suggestion
|tpahere <player>|Envoie une demande pour tp un joueur sur soi|
```

2023-03-14 17:13 UTC, dadodasyra commented on commands/general-commands.md
> +|hdv sell <montant>|Permet de vendre les items en main au hdv|
Quitte à donner les sous commande autant parler du /hdv search par exemple

2023-03-14 17:13 UTC, dadodasyra commented on commands/general-commands.md
> +|trade accept|Accepte une demande de tarde|
```suggestion
|trade accept|Accepte une demande de trade|
```

2023-03-14 17:13 UTC, dadodasyra commented on commands/general-commands.md
> +|mymoney|Permet de voir son argent|
```suggestion
|money|Permet de voir son argent|
```
Est le nom exact dans le code, mymoney est un alias

2023-03-14 17:13 UTC, dadodasyra commented on commands/general-commands.md
> +|clear|Permet de clear l'intégralité de son inventaire |
Je ne crois pas que cette commande soit accessible par les joueurs, à vérif

2023-03-14 17:13 UTC, dadodasyra commented on commands/general-commands.md
> +|tps|Affiche les TPS du monde|
```suggestion
|tps|Affiche les TPS du serveur sur lequel vous êtes connecté|
```

2023-03-14 17:13 UTC, dadodasyra commented on commands/general-commands.md
> +|suicide|Permet de mourire|
Commande vanilla et discutable de si on devrait la décrire dans ce tableau, sinon ce serait /kill au passage, "permet de mourire" veut rien dire et est gramatiquement faux

2023-03-14 17:13 UTC, dadodasyra commented on commands/general-commands.md
> +
Une description doit être rajouté ici en disant que toutes les commandes accessible au vip sont accessible aux inter etc.., puis on peut dégager le "et +" dans la liste ci-dessous

2023-03-14 17:13 UTC, dadodasyra commented on commands/general-commands.md
> +|prefix <prefix> |  | Oméga Perso et + |
Je pense très honnêtement que tu en as oublié quelques une

2023-03-14 17:13 UTC, dadodasyra commented on commands/general-commands.md
> +|freerepair [all] | Répare l'item de votre main ou tout les items de votre inventaire  gratuitement | VIP et + |
```suggestion
|freerepair [all] | Répare l'item de votre main ou tout les items de votre inventaire gratuitement | VIP et + |
```

2023-03-14 17:13 UTC, dadodasyra commented on commands/general-commands.md
> +|ceshop |  | Oméga et + |
Détail ?? Descritpion ?

2023-03-14 17:55 UTC, CercleTour commented
Normalement c'est bon

2023-03-15 14:35 UTC, zelytra commented
Cette PR correspond a quel tâche ? Tu as regroupé toutes les commandes du jeux sur la même page ?
Les tâches demande de séparer les commandes sous forme de groupe

2023-03-16 15:50 UTC, CercleTour commented
Les commandes doivent être sur la même page. Il y a uniquement les commandes de général et les commandes de faction. C'est une seul PR. Il ne faut pas suivre ce que quasar a mis, c'était juste pour suivre plus finement les commandes.

2023-03-16 16:23 UTC, zelytra commented
Dans ce cas je pousse la demande sous accord de @dadodasyra de séparer les commandes en plusieurs documents comme le pousse les taches.

Pour raison de lisibilité et de recherche d'informations plus efficaces.

2023-03-17 15:47 UTC, dadodasyra commented on commands/general-commands.md
> +|hdv sell <montant>|Permet de vendre les items en main au hdv|
Je vais..

2023-03-17 15:47 UTC, dadodasyra commented on commands/general-commands.md
> +|hdv sell <montant>|Permet de vendre les items en main au hdv|
Il sert à quoi le salon #report-bug sur discord ?

2023-03-17 16:00 UTC, CercleTour commented on commands/general-commands.md
> +|hdv sell <montant>|Permet de vendre les items en main au hdv|
je vien de le trouvé, personne n'utilise cette commande :kappa:

2023-03-17 16:00 UTC, CercleTour commented on commands/general-commands.md
> +|hdv sell <montant>|Permet de vendre les items en main au hdv|
trouver*

2023-03-17 16:02 UTC, zelytra approved these changes

2023-03-17 16:03 UTC, dadodasyra commented on commands/general-commands.md
> +|hdv sell <montant>|Permet de vendre les items en main au hdv|
bah justement ? elle marche pas ou personne l'utilise

2023-03-20 05:32 UTC, zelytra commented
@dadodasyra

2023-03-20 18:27 UTC, dadodasyra requested changes

2023-03-20 18:27 UTC, dadodasyra commented on commands/jobs-commands.md
> +Les commandes sont un outil incontournable pour améliorer votre expérience de jeu sur Histeria. Vous pourrez utiliser ces commandes pour effectuer diverses actions, telles que la création de homes, l
encore un copier coller

2023-03-20 18:27 UTC, dadodasyra commented on commands/jobs-commands.md
> +|job|Permet d'afficher la liste des métiers|
une page vide, ça n'a rien à faire dans un fichier à part

2023-03-21 17:27 UTC, dadodasyra requested changes
et btw tes noms de fichers sont en français (gradee est nul btw) alors que la fin est en anglais (commands)

2023-03-21 17:27 UTC, dadodasyra commented on commands/economie-commands.md
> +## Les commandes de jobs
qu'est ce que ça branle dans economy command ?

2023-03-21 17:27 UTC, dadodasyra commented on commands/gradee-commands.md
> +Les Donnateur ont accès à toutes les commandes
```suggestion
Les Donateurs ont accès à toutes les commandes
```

2023-03-21 17:27 UTC, dadodasyra commented on commands/gradee-commands.md
> +Les commandes pour Omég sont accessibles également aux et Donateur.
```suggestion
Les commandes pour Omégas sont accessibles également aux Donateurs.
```

2023-03-21 17:27 UTC, dadodasyra commented on commands/gradee-commands.md
> +Les commandes pour VIP sont accessibles également aux Interplanétaires, Oméga, et Donateur.
```suggestion
Les commandes pour VIP sont accessibles également aux Interplanétaires, Omégas, et Donateurs.
```

2023-03-21 17:27 UTC, dadodasyra commented on commands/gradee-commands.md
> +|prefix <prefix> |Permet d'afficher un préfixe personnalisé| Donateur |
```suggestion
|prefix <prefix> |Permet d'afficher un préfixe personnalisé| Donateur & Prefix dynamique |
```

2023-03-21 17:27 UTC, dadodasyra commented on commands/home-et-tp-commands.md
> +Notre serveur propose un système de téléportation qui vous permet de vous déplacer facilement entre les différentes arènes, factions, minages et le lobby. Vous pouvez également envoyer des demandes d
```suggestion
Notre serveur propose un système de téléportation qui vous permet de vous déplacer facilement entre les différentes arènes, factions, minages et le lobby. Vous pouvez également envoyer des demandes de téléportation pour vous téléporter vers des joueurs ou de les téléporter vers vous. Les homes vous permettront de créer des points de téléportation personnalisés vers vos bases, vos fermes, pillages.. 
```

2023-03-21 17:27 UTC, dadodasyra commented on commands/home-et-tp-commands.md
> +|lobby [nombre]|Permet de se téléporter a un lobby|
```suggestion
|lobby [nombre]|Permet de se téléporter à un lobby|
```
Je refuse de croire que c'est moi qui ai fait cette faute

2023-03-21 19:34 UTC, CercleTour commented on commands/economie-commands.md
> +## Les commandes de jobs
Car ça permet d'avoir du stuff en soit

2023-03-21 20:36 UTC, dadodasyra commented on commands/economie-commands.md
> +## Les commandes de jobs
ça n'a aucun rapport, calendar non plus, en fait trop de truc, economie c'est tout ce qui touche l'argent et/ou l'échange de iben

2023-03-21 20:41 UTC, dadodasyra requested changes
Si tu lisais correctement et utilisait les commit de suggestions j'aurais pas eu besoin de refaire cette review en request changes

2023-03-21 20:41 UTC, dadodasyra commented on commands/graded-commands.md
> +Les Donnateurs ont accès à toutes les commandes
```suggestion
Les Donateurs ont accès à toutes les commandes
```
pour la 3ème fois

2023-03-21 20:41 UTC, dadodasyra commented on commands/home-and-tp-commands.md
> +Notre serveur propose un système de téléportation qui vous permet de vous déplacer facilement entre les différentes arènes, factions, minages et le lobby. Vous pouvez également envoyer des demandes d
```suggestion
Notre serveur propose un système de téléportation qui vous permet de vous déplacer facilement entre les différentes arènes, factions, minages et le lobby. Vous pouvez également envoyer des demandes de téléportation pour vous téléporter vers des joueurs ou de les téléporter vers vous. Les homes vous permettront de créer des points de téléportation personnalisés vers vos bases, vos fermes, pillages..
```
2ème fois

2023-03-23 14:24 UTC, zelytra requested changes
Faut se mettre d'accord sur le fais de mettre la commande dans le tableau avec ou sans le / et en plus de le mettre en format code ou non. Tu alterne entre les documents ta facon de rediger. Il faut choisir

2023-03-24 08:44 UTC, zelytra requested changes

2023-03-24 08:44 UTC, zelytra commented on commands/economy-commands.md
> +<args> = Argument obligatoire.
'<' non pris en compte

2023-03-24 08:44 UTC, zelytra commented on commands/general-commands.md
> +<args> = Argument obligatoire.
'<' non pris en compte

2023-03-24 08:44 UTC, zelytra commented on commands/graded-commands.md
> +<args> = Argument obligatoire.
'<' non pris en compte

2023-03-24 08:44 UTC, zelytra commented on commands/home-and-tp-commands.md
> +<args> = Argument obligatoire.
'<' non pris en compte

2023-03-24 09:32 UTC, dadodasyra commented on commands/economy-commands.md
> +<args> = Argument obligatoire.
Même moi je comprends pas là, il doit le backslash ?

2023-03-24 16:23 UTC, zelytra approved these changes

2023-03-24 18:07 UTC, dadodasyra approved these changes

2023-03-24 18:07 UTC, merged