Ajout des enchantements
HisteriaMC/histeria-wiki pull request #12
Opened 2023-03-14 18:22 UTC by ItamSurMc

2023-03-14 18:35 UTC, zelytra commented
Aucune icone n'as été mis dans les pages. Cf [wiki](https://histeria.zelytra.fr/wiki/developer/wiki-good-practice)

2023-03-15 14:52 UTC, zelytra requested changes
Il faut faire des lignes a tes tableaux, les retour a la ligne ne sont pas dutout ce qu'il faut faire

2023-03-16 21:28 UTC, zelytra requested changes

2023-03-16 21:28 UTC, zelytra commented on enchants/dragonbreath.md
> +    <th>Pourcentages d'activation</th>>
fermeture de balise en trop
```suggestion
    <th>Pourcentages d'activation</th>
```

2023-03-16 21:31 UTC, zelytra approved these changes

2023-03-17 15:31 UTC, dadodasyra requested changes
Voir le seul commentaire qui est valable pour tout les enchantements.
On ne tutoie pas on parle de manière informelle ou alors on vouvoie. 
Et "en ennemi" veut rien dire dans ce contexte
+ redirections sur les autres pages quand nécessaire

2023-03-19 09:40 UTC, dadodasyra requested changes

2023-03-19 09:40 UTC, dadodasyra commented on enchants/adrenaline.md
> +Quand un ennemi est frappé avec cet enchantement, il a une chance de donner Force 3 pour 2 secondes et de heal une petite quantité de vie toutes les secondes (3 secondes) au porteur.
```suggestion
Quand un ennemi est frappé avec cet enchantement, il a une chance de donner Force 3 pour 2 secondes et de heal une petite quantité de vie toutes les secondes (pendant 3 secondes) au porteur.  
```

2023-03-19 09:40 UTC, dadodasyra commented on enchants/attraction.md
> +  <tr>
On a encore du tutoiement et la répétition d'ennemi

2023-03-19 09:40 UTC, dadodasyra commented on enchants/bleeding.md
> +Quand un ennemi est frappé avec cet enchantement, il a une chance de lui infliger des dégats toutes les secondes (5 secondes).
```suggestion
Quand un ennemi est frappé avec cet enchantement, il a une chance de lui infliger des dégats toutes les secondes (pendant 5 secondes).  
```

2023-03-19 09:40 UTC, dadodasyra commented on enchants/freeze.md
> +L'enchantement *Freeze* est fusionnable à une Epéé en Histerite. L'enchantement *Freeze* est incompatible avec l'enchantement *Hypothermia*.
Répétition enchantement freeze et manque tjr la redirection

2023-03-19 09:40 UTC, dadodasyra commented on enchants/strike.md
> +Quand un ennemi est frappé avec cet enchantement, il a une chance de le foudroyer et de lui infliger des dégats (l'éclair ne fait pas dégats additionnels).
```suggestion
Quand un ennemi est frappé avec cet enchantement, il a une chance de le foudroyer et de lui infliger des dégats (l'éclair ne fait pas de dégats additionnels).  
```

2023-03-20 18:35 UTC, dadodasyra requested changes

2023-03-20 18:35 UTC, dadodasyra commented on enchants/attraction.md
> +L'enchantement *Attraction* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```suggestion
L'enchantement *Attraction* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```

2023-03-20 18:35 UTC, dadodasyra commented on enchants/bleeding.md
> +L'enchantement *Bleeding* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```suggestion
L'enchantement *Bleeding* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```

2023-03-20 18:35 UTC, dadodasyra commented on enchants/demonic.md
> +L'enchantement *Demonic* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```suggestion
L'enchantement *Demonic* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```

2023-03-20 18:35 UTC, dadodasyra commented on enchants/dragonbreath.md
> +L'enchantement *DragonBreath* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```suggestion
L'enchantement *DragonBreath* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```

2023-03-20 18:35 UTC, dadodasyra commented on enchants/fatigue.md
> +L'enchantement *Fatigue* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```suggestion
L'enchantement *Fatigue* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```

2023-03-20 18:35 UTC, dadodasyra commented on enchants/fatigue.md
> +Quand un ennemi est frappé avec cet enchantement, il a une chance de lui donner l'effet Mining Fatigue au niveau 3 (4 secondes).
```suggestion
Quand un ennemi est frappé avec cet enchantement, il a une chance de lui donner l'effet Mining Fatigue au niveau 3 (pendant 4 secondes).  
```

2023-03-20 18:35 UTC, dadodasyra commented on enchants/fluctuation.md
> +L'enchantement *Fluctuation* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```suggestion
L'enchantement *Fluctuation* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```

2023-03-20 18:35 UTC, dadodasyra commented on enchants/hunger.md
> +L'enchantement *Hunger* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```suggestion
L'enchantement *Hunger* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```

2023-03-20 18:35 UTC, dadodasyra commented on enchants/freeze.md
> +L'enchantement *Freeze* est fusionnable à une Epéé en Histerite. Cet enchantement est incompatible avec l'enchantement [*Hypothermia*](https://histeria.fr/wiki/enchants/hypothermia).
```suggestion
L'enchantement *Freeze* est fusionnable à une Epéé en Histerite. Cet enchantement est incompatible avec l'enchantement [*Hypothermia*](https://histeria.fr/wiki/enchants/hypothermia).
```

2023-03-20 18:35 UTC, dadodasyra commented on enchants/narcotic.md
> +L'enchantement *Narcotic* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```suggestion
L'enchantement *Narcotic* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```

2023-03-20 18:35 UTC, dadodasyra commented on enchants/narcotic.md
> +Quand tu frappes en ennemi avec cet enchantement, il a une chance de lui donner l'effet Poison au niveau 1 (4 secondes).
Toujours du tutoiement

2023-03-20 18:35 UTC, dadodasyra commented on enchants/reborn.md
> +L'enchantement *Reborn* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```suggestion
L'enchantement *Reborn* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```

2023-03-20 18:35 UTC, dadodasyra commented on enchants/rust.md
> +L'enchantement *Rust* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```suggestion
L'enchantement *Rust* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```

2023-03-20 18:35 UTC, dadodasyra commented on enchants/soulsteal.md
> +L'enchantement *SoulSteal* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```suggestion
L'enchantement *SoulSteal* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```

2023-03-20 18:35 UTC, dadodasyra commented on enchants/soulsteal.md
> +Quand un ennemi est frappé avec cet enchantement, il a une chance de te donner Haste 2 pour 2 secondes et de lui voler 0,5 coeur.
toujours tutoyé

2023-03-20 18:35 UTC, dadodasyra commented on enchants/split.md
> +L'enchantement *Split* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```suggestion
L'enchantement *Split* est fusionnable à une Epéé en Histerite. Aucune incompatibilité.
```

2023-03-20 18:35 UTC, dadodasyra commented on enchants/strike.md
> +L'enchantement *Attraction* est fusionnable à une Epéé en Histerite. Cet enchantement est incompatible avec l'enchantement [*Execution*](https://histeria.fr/wiki/enchants/execution).
```suggestion
L'enchantement *Attraction* est fusionnable à une Epéé en Histerite. Cet enchantement est incompatible avec l'enchantement [*Execution*](https://histeria.fr/wiki/enchants/execution).
```

2023-03-20 22:44 UTC, dadodasyra requested changes
- [ ] Tout les niveau maximum décaler le gras à droite du : 
- [ ] "à une Epéé en Histerite" vers "avec une épée en Histerite"
- [ ] "dégats" avec "dégâts"

2023-03-20 22:44 UTC, dadodasyra commented on enchants/adrenaline.md
> +**Niveau maximum** : 5
```suggestion
**Niveau maximum :** 5
```

2023-03-20 22:44 UTC, dadodasyra commented on enchants/demonic.md
> +Quand un ennemi est frappé avec cet enchantement, il a une chance de lui donner l'effet Wither au niveau 1 (4 secondes).
```suggestion
Quand un ennemi est frappé avec cet enchantement, il a une chance de lui donner l'effet Wither au niveau 1 (pendant 4 secondes).  
```

2023-03-20 22:44 UTC, dadodasyra commented on enchants/dragonbreath.md
> +Quand un ennemi est frappé avec cet enchantement, il a une chance de lui envoyer une boule de feu qui lui causera 1,5 coeurs de dégats.
```suggestion
Quand un ennemi est frappé avec cet enchantement, il a une chance de lui envoyer une boule de feu qui lui causera 1,5 coeur de dégats.  
```

2023-03-20 22:44 UTC, dadodasyra commented on enchants/narcotic.md
> +Quand un ennemi est frappé avec cet enchantement, il a une chance de lui donner l'effet Poison au niveau 1 (4 secondes).
```suggestion
Quand un ennemi est frappé avec cet enchantement, il a une chance de lui donner l'effet Poison au niveau 1 (pendant 4 secondes).  
```

2023-03-20 22:44 UTC, dadodasyra commented on enchants/reborn.md
> +Quand un ennemi est frappé avec cet enchantement, il a une chance de te soigner complètement.
```suggestion
Quand un ennemi est frappé avec cet enchantement, il a une chance de soigner son porteur complètement.  
```

2023-03-20 22:44 UTC, dadodasyra commented on enchants/rust.md
> +Quand un ennemi est frappé avec cet enchantement, il a une chance de lui retirer plus de durabilité sur son armure (1% durabilité totale).
```suggestion
Quand un ennemi est frappé avec cet enchantement, il a une chance de lui retirer plus de durabilité sur son armure (1% de la durabilité totale).  
```

2023-03-20 22:44 UTC, dadodasyra commented on enchants/soulsteal.md
> +Quand un ennemi est frappé avec cet enchantement, il a une chance de donner Haste 2 pour 2 secondes et de lui voler 0,5 coeur au joueur ayant donné le cou^p.
```suggestion
Quand un ennemi est frappé avec cet enchantement, il a une chance de donner Haste 2 pour 2 secondes et de lui voler 0,5 coeur au joueur ayant donné le coup.  
```

2023-03-21 20:47 UTC, dadodasyra requested changes

2023-03-21 21:55 UTC, dadodasyra approved these changes

2023-03-24 08:40 UTC, zelytra approved these changes

2023-03-24 09:38 UTC, dadodasyra approved these changes

2023-03-24 09:38 UTC, merged