Ajout enchants2
HisteriaMC/histeria-wiki pull request #124
Opened 2023-03-20 20:34 UTC by ItamSurMc

2023-03-20 21:34 UTC, zelytra approved these changes

2023-03-20 22:56 UTC, dadodasyra requested changes
- [ ] "à une armure en Histerite ou en Nocturite" en "avec une pièce d'armure"
- [ ] "**Niveau maximum** :" -> "**Niveau maximum :**"
- [ ] "Il à" en "Il a"

2023-03-20 22:56 UTC, dadodasyra commented on enchants/blasphemy.md
> +L'enchantement *Blasphemy* est fusionnable à une armure en Histerite ou en Nocturite.L'enchantement est incompatible avec l'enchantement [*Dodge*](https://histeria.fr/wiki/enchants/dodge).
```suggestion
L'enchantement *Blasphemy* est fusionnable à une pièce d'armure. L'enchantement est incompatible avec [*Dodge*](https://histeria.fr/wiki/enchants/dodge).
```

2023-03-20 22:56 UTC, dadodasyra commented on enchants/conceal.md
> +Quand le porteur de l'enchantement est frappé, il à une chance de cacher l'indicateur de vie (dans le nom du porteur de l'enchantement) pour 6 secondes.
```suggestion
Quand le porteur de l'enchantement est frappé, il a une chance de cacher l'indicateur de vie (dans le nom du porteur de l'enchantement) pour 6 secondes.  

```

2023-03-20 22:56 UTC, dadodasyra commented on enchants/dodge.md
> +Quand le porteur de l'enchantement est frappé, il à une chance de bloquer les dégats reçus.
```suggestion
Quand le porteur de l'enchantement est frappé, il a une chance de bloquer les dégats reçus.    

```

2023-03-20 22:56 UTC, dadodasyra commented on enchants/dodge.md
> +L'enchantement *Dodge* est fusionnable à une armure en Histerite ou en Nocturite.L'enchantementest incompatible avec l'enchantement [*Blasphemy*](https://histeria.fr/wiki/enchants/blasphemy).
```suggestion
L'enchantement *Dodge* est fusionnable avec une pièce d'armure. L'enchantement est incompatible avec [*Blasphemy*](https://histeria.fr/wiki/enchants/blasphemy).

```

2023-03-21 21:11 UTC, dadodasyra approved these changes

2023-03-21 21:13 UTC, merged