Enchantements d'arène
HisteriaMC/histeria-wiki pull request #129
Opened 2023-03-21 20:37 UTC by ItamSurMc

2023-03-21 21:36 UTC, dadodasyra requested changes
- [ ] Respecte pas le format pour les icons cf doc sur le wiki
- [x] obtensible -> obtenable
- [x] avec épée en Histerite -> avec une épée en Histerite

2023-03-21 21:36 UTC, dadodasyra commented on enchants/eclipse.md
> +L'enchantement *Eclipse* est fusionnable avec une pièce d'armure, il n'est obtensible que dans les coffres d'arènes. L'enchantement est incompatible avec tout les autres enchantements d'arène et les
```suggestion
L'enchantement *Eclipse* est fusionnable avec une pièce d'armure, il est obtenable que dans les coffres d'arènes. L'enchantement est incompatible avec tout les autres enchantements d'arène et les enchantements obtenable en tuant des [boss](https://histeria.fr/wiki/boss).

```

2023-03-21 21:36 UTC, dadodasyra commented on enchants/eclipse.md
> +Quand le porteur de l'enchantement est frappé par un ennemi, cet enchantement a une chance de lui donner l'effet Cécité 3 pour 3 secondes et inflige également 0,5 coeur de dégâts.
```suggestion
Quand le porteur de l'enchantement est frappé par un ennemi, cet enchantement a une probabilité de lui donner l'effet Cécité 3 pendant 3 secondes et de lui infliger par la même occasion 0,5 coeur de dégâts.
```

2023-03-21 21:36 UTC, dadodasyra commented on enchants/hypothermia.md
> +Quand un ennemi est frappé avec cet enchantement, il a une chance de lui retirer l'effet Resistance au Feu, le freeze pour 3 secondes et lui infliger 0,75 coeur de dégâts.
```suggestion
Quand un ennemi est frappé avec cet enchantement, il a une chance de lui retirer l'effet Resistance au Feu, ainsi que de le freeze pendant 3 secondes et de lui infliger 0,75 coeur de dégâts.

```

2023-03-21 21:36 UTC, dadodasyra commented on enchants/lunarstrike.md
> +Quand un ennemi est frappé avec cet enchantement, il a une chance de lui rallonger tous ses cooldowns de 5 secondes, de le foudroyer, ainsi que de lui infliger 1,25 coeurs de dégâts.
```suggestion
Quand un ennemi est frappé avec cet enchantement, il a une chance de lui rallonger tous ses cooldowns de 5 secondes, de le foudroyer, ainsi que de lui infliger 1,25 coeur de dégâts.

```

2023-03-21 21:36 UTC, dadodasyra commented on enchants/magic.md
> +Quand un ennemi est frappé avec cet enchantement, il a une chance de lui donner des effets : Nausée 3 pour 5 secondes, Cécité 3 pour 4 secondes, Lenteur 3 pour 5 secondes.
```suggestion
Quand un ennemi est frappé avec cet enchantement, il a une chance de lui donner des effets : Nausée 3 pendant 5 secondes, Cécité 3 pendant 4 secondes et Lenteur 3 pendant 5 secondes.

```

2023-03-21 21:36 UTC, dadodasyra commented on enchants/permaflame.md
> +Quand un ennemi est frappé avec cet enchantement, il a une chance de retirer l'effet Resistance au Feu, infliger 0,5 coeur de dégât et mettre en feu pour 30 secondes tous les ennemis dans un rayon de
```suggestion
Quand un ennemi est frappé avec cet enchantement, il a une chance de retirer l'effet Résistance au Feu, d'infliger 0,5 coeur de dégât et de mettre en feu pendant 30 secondes tous les ennemis dans un rayon de 10 blocs.

```

2023-03-21 21:36 UTC, dadodasyra commented on enchants/revive.md
> +Quand le porteur de l'enchantement est frappé par un ennemi, cet enchantement a une chance  soigner le porteur de l'enchantement de 3 coeurs.
```suggestion
Quand le porteur de l'enchantement est frappé par un ennemi, cet enchantement a une chance de soigner le porteur de 3 coeurs.

```

2023-03-22 17:21 UTC, dadodasyra commented
Aucun de mes commentaires n'ont été vraiment résolu bien que tu les a marqué comme resolve !

2023-03-22 21:09 UTC, dadodasyra approved these changes

2023-03-23 14:21 UTC, zelytra approved these changes

2023-03-23 14:22 UTC, merged