Ajout des enchantements de boss
HisteriaMC/histeria-wiki pull request #130
Opened 2023-03-22 15:01 UTC by ItamSurMc

2023-03-22 15:23 UTC, zelytra approved these changes

2023-03-22 17:34 UTC, dadodasyra requested changes
- [ ] L'enchantement est incompatible avec tout les enchantements d'arène. -> L'enchantement est incompatible avec les enchantements d'arène.
- [ ] tutant -> tuant

2023-03-22 17:34 UTC, dadodasyra commented on enchants/tsunami.md
> +L'enchantement *Tsunami* est fusionnable avec une [épée en Histerite](https://histeria.fr/wiki/tools/histerite-sword), il est obtenable seulement en tuant un [boss](https://histeria.fr/wiki/boss). L'
```suggestion
L'enchantement *Tsunami* est fusionnable avec une [épée en Histerite](https://histeria.fr/wiki/tools/histerite-sword), il est obtenable seulement en tuant un [boss](https://histeria.fr/wiki/boss). L'enchantement est incompatible avec tous les enchantements d'arène.
```

2023-03-24 17:17 UTC, zelytra approved these changes

2023-03-24 17:17 UTC, merged