Ajout du dossier rewards
HisteriaMC/histeria-wiki pull request #135
Opened 2023-03-24 19:45 UTC by ItamSurMc

2023-03-24 20:14 UTC, dadodasyra commented
Très honnêtement c'était pas forcément le meilleur truc à commencer prcq c'est des trucs qui devraient venir à changer en fait. Du genre c'est pas du tout balance et c'est des rewards V5 jamais changé

2023-10-02 14:57 UTC, zelytra commented
Ca donne quoi ici ?

2023-10-10 10:14 UTC, zelytra requested changes
Manque les nom custom FR

2023-10-26 08:03 UTC, zelytra commented
Up ?

2023-11-06 08:20 UTC, zelytra commented
Up ?

2023-11-06 09:21 UTC, dadodasyra commented
C'était une draft et avait été pausé prcq on était pas encore sur de si ça change

2023-11-06 09:22 UTC, zelytra commented
Il faut close si plus d'actualité, car la on est sur un bon outdated

2023-11-06 09:25 UTC, dadodasyra requested changes
Faudra changer tous les liens de redirection aussi, encore un état de draft à ce que je vois

2023-11-06 09:25 UTC, dadodasyra commented on rewards/calandar-rewards.md
> +| 2                         | Tout les [outils Histerite](https://histeria.fr/wiki/tools)                                                                                             |
Tous

2023-11-06 09:25 UTC, dadodasyra commented on rewards/calandar-rewards.md
> +| 7                         | 128 Cobblestone compressé                                                                                                                               |
pluriel

2023-11-06 09:25 UTC, dadodasyra commented on rewards/calandar-rewards.md
> +| 14                        | 16 [ascenceurs](https://histeria.fr/wiki/blocks/elevator)                                                                                               |
ascenseur

2023-11-06 09:25 UTC, dadodasyra commented on rewards/calandar-rewards.md
> +| 15                        | Code promo 20pour. sur la boutique bedrock                                                                                                              |
pour. remplacable par %, in game il est écrit comme ça prcq % s'affiche pas

2023-11-06 09:25 UTC, dadodasyra commented on rewards/calandar-rewards.md
> +| 21                        | 16 [boîtes à rangement](https://histeria.fr/wiki/blocks/drawer)                                                                                         |
on dit fils de pute, pas fils à pute

2023-11-06 09:25 UTC, dadodasyra commented on rewards/calandar-rewards.md
> +| 22                        | 48 [améliorationd de boîte à rangement](https://histeria.fr/wiki/items/drawer-upgrade)                                                                  |
typo

2023-11-06 09:25 UTC, dadodasyra commented on rewards/calandar-rewards.md
> +| 40                        | Grade Omega pendant 2 semaines                                                                                                                          |
lien boutique ?

2023-11-06 09:25 UTC, dadodasyra commented on rewards/calandar-rewards.md
> +| 60                        | Code promo 40% pour sur la boutique bedrock                                                                                                             |
lien boutique ?

2023-11-06 09:25 UTC, dadodasyra commented on rewards/calandar-rewards.md
> +| 105                       | Grade Omega pendant 2 semaines                                                                                                                          |
boutique

2023-11-06 09:25 UTC, dadodasyra commented on rewards/calandar-rewards.md
> +| 155                       | 5 Clé en Nocturite                                                                                                                                      |
pluriel

2023-11-06 09:25 UTC, dadodasyra commented on rewards/farmer-rewards.md
Ca a changé en V6.5.1

2023-11-06 09:25 UTC, dadodasyra commented on rewards/tableau.md
wtf ???

2024-01-09 18:11 UTC, ItamSurMc commented
@Tonmou8128 tu pourrai faire ca ? Je te passe les toutes les infos stv. Celles déja mises sont celles de l'ancienne version.

2024-01-09 20:15 UTC, Tonmou8128 commented
> @Tonmou8128 tu pourrai faire ca ? Je te passe les toutes les infos stv. Celles déja mises sont celles de l'ancienne version.

Pas de problème, dès que tu me donnes les infos et que j'ai le temps je le ferai

2024-01-09 20:16 UTC, Tonmou8128 commented
Et pour le fonctionnement de GitHub que je maîtrise moyennement, le plus simple pour moi serait de fermer cette PR et d'en créer une nouvelle
Après s'il y a une autre solution faut juste m'expliquer

2024-01-12 19:20 UTC, Tonmou8128 commented
> Et pour le fonctionnement de GitHub que je maîtrise moyennement, le plus simple pour moi serait de fermer cette PR et d'en créer une nouvelle Après s'il y a une autre solution faut juste m'expliquer

@ItamSurMc Tu peux fermer cette PR ?

2024-01-12 22:35 UTC, closed without merging