Ajout de l'Hist Anvil (.png et .md)
HisteriaMC/histeria-wiki pull request #142
Opened 2023-04-04 16:25 UTC by CercleTour

2023-04-04 16:47 UTC, zelytra commented
Il manque la table de craft

2023-04-04 17:09 UTC, zelytra commented
Ah savais pas ok

2023-04-04 17:09 UTC, zelytra approved these changes

2023-04-05 20:23 UTC, dadodasyra requested changes

2023-04-05 20:23 UTC, dadodasyra commented on blocks/histerite-anvil.md
> +Cette enclume vous permettra d'enchanter vos équipements, d'améliorer les enchantements déjà présents avec des parchemin d'enchantement mais également d'ajouter un Kill Tag sur votre épée. Trouvable
Rediriger vers la page "serveurs factions" et vers kill tag.
Et répétition pour la commande /fusion

2023-04-06 15:27 UTC, CercleTour commented
Il faut me mettre l'Issue kill tag (#35) aussi du coup

2023-04-07 15:39 UTC, zelytra requested changes
Lien de redirections mauvais

2023-04-08 12:16 UTC, zelytra approved these changes
@dadodasyra

2023-04-08 12:28 UTC, dadodasyra requested changes
En plus des coms, ça me dérange un peu le fait que la catégorie utilité soit en réalité un complément à description, en vérité tu donnes déjà l'utilité de l'item dans la description donc le nom de la catégorie n'a plus trop de sens

2023-04-08 12:28 UTC, dadodasyra commented on blocks/histerite-anvil.md
> +Les enclumes en histerite sont des enclumes customisées présentes sur le serveur. Elles sont trouvables au spawn des [factions](https://histeria.fr/wiki/worlds/serveurs-faction) mais ne sont pas obte
```suggestion
Les enclumes en histerite sont des enclumes customisées présentes sur le serveur. Elles se trouvent au spawn des [serveurs factions](https://histeria.fr/wiki/worlds/serveurs-faction), mais elles ne sont ni obtenables ni craftables. Vous pouvez également y accéder grâce à la commande /fusion si vous possédez le grade suffisant pour l'utiliser (voir les [commandes gradées](https://histeria.fr/wiki/commands/graded-commands)).
```

2023-04-08 12:28 UTC, dadodasyra commented on blocks/histerite-anvil.md
> +Cette enclume vous permettra d'enchanter vos équipements, d'améliorer les enchantements déjà présents avec des parchemin d'enchantement mais également d'ajouter un [Kill Tag](https://histeria.fr/wiki
```suggestion
Cette enclume vous permettra d'enchanter vos équipements, d'améliorer les enchantements déjà présents avec des parchemin d'enchantement mais également d'ajouter un [Kill Tag](https://histeria.fr/wiki/item/kill-tag) sur votre épée.
```

2023-04-08 12:28 UTC, dadodasyra commented on items/kill-tag.md
> +Les kill tag sont des badges que vous pouvez mettre sur vos armes grâces aux [enclumes en histerite](https://histeria.zelytra.fr/wiki/blocks/histerite-anvil). Ils permettent d'afficher un message cus
```suggestion
Les kill tag sont des badges que vous pouvez mettre sur vos armes grâce aux [enclumes en histerite](https://histeria.zelytra.fr/wiki/blocks/histerite-anvil). Ils permettent d'afficher un message customisé dans le chat lorsque vous tuez un joueur avec une arme en possèdent un. Vous pouvez uniquement en obtenir en utilisant les [clés en nocturite](https://histeria.zelytra.fr/wiki/items/nocturite-key) ainsi qu'à des rares évènements organisés par le staff.
```

2023-04-08 12:28 UTC, dadodasyra commented on items/kill-tag.md
> +Il existe de nombreux kill tag avec des messages différents et de rareté différentes selon le message. Les kill tag sont uniquement cosmétique. Attention, une fois un kill tag mis sur une arme, il ne
```suggestion
Il existe de nombreux kill tag avec des messages différents et de raretés différentes selon le message. Les kill tag sont uniquement à des fins cosmétiques. Attention, une fois un kill tag mis sur une arme, il ne pourra pas être récupéré, bien qu'il restera possible de le remplacer par un nouveau.
```

2023-04-10 13:39 UTC, zelytra approved these changes
@dadodasyra

2023-04-21 13:45 UTC, dadodasyra requested changes

2023-04-21 13:45 UTC, dadodasyra commented on items/kill-tag.md
> +Les kill tag sont des badges que vous pouvez mettre sur vos armes grâce aux [enclumes en histerite](https://histeria.zelytra.fr/wiki/blocks/histerite-anvil). Ils permettent d'afficher un message cust
pas les bons liens

2023-04-23 14:39 UTC, dadodasyra approved these changes

2023-04-23 14:39 UTC, merged