Premier block
HisteriaMC/histeria-wiki pull request #144
Opened 2023-04-13 20:52 UTC by QuasterX

2023-04-13 21:05 UTC, dadodasyra commented
Fini ou pas ? si non, c'est à mettre en draft

2023-04-13 21:06 UTC, dadodasyra requested changes

2023-04-13 21:06 UTC, dadodasyra commented on blocks/spike.md
> +Les spikes (ou piques) sont fait à base d'histerite qui permet de défendre la base.
L'histerite permet de défendre la base ? hein ?

2023-04-13 21:06 UTC, dadodasyra commented on blocks/spike.md
> +Les spikes permettent d'ajouter une défense supplémentaire à la base et inflige des dégâts au contact. Très utile contre les envahisseurs!
la base ? la quelle, y en a une précise ?

2023-04-16 09:34 UTC, zelytra requested changes

2023-04-16 09:34 UTC, zelytra commented on blocks/drawer.md
> + ==-
```suggestion
 ==-  
```

2023-04-16 09:34 UTC, zelytra commented on blocks/drawer.md
> +## Craft
```suggestion
## Craft  
```

2023-04-16 09:34 UTC, zelytra commented on blocks/spike.md
> + ==-
```suggestion
 ==- 
```

2023-04-16 09:34 UTC, zelytra commented on blocks/spike.md
> +## Craft
```suggestion
## Craft  
```

2023-05-01 19:37 UTC, dadodasyra commented on blocks/spike.md
> +## Craft
Pourquoi ?

2023-05-01 19:37 UTC, dadodasyra commented on blocks/drawer.md
> +## Craft
Pourquoi ?

2023-07-11 21:55 UTC, dadodasyra commented
Poke

2023-10-02 14:55 UTC, zelytra commented
@ItamSurMc la PR est outdated, trop de retard. Reprend ce dont tu as besoins dedans puis recreer une PR avec les modifs presante ici

2023-10-07 14:11 UTC, closed without merging