Add some items
HisteriaMC/histeria-wiki pull request #146
Opened 2023-04-25 10:30 UTC by CercleTour

2023-04-25 10:32 UTC, CercleTour commented
Il y a #50 , #51 , #47 , #48 , #49

2023-04-25 11:47 UTC, zelytra approved these changes

2023-05-01 19:34 UTC, dadodasyra requested changes

2023-05-01 19:34 UTC, dadodasyra commented on items/compress-cobble.md
> +La pierre compressé est un condensé de pierre qui vous permettra d'obtenir des minerais en les ouvrant dans les cobbles breakers. Ceux-ci sont trouvables dans le spawn des [serveurs faction](https://
```suggestion
La pierre compressée est un condensé de pierre qui vous permettra d'obtenir des minerais en les ouvrant dans les cobbles breakers. Ceux-ci sont trouvables dans le spawn des [serveurs factions](https://histeria.fr/wiki/worlds/serveurs-faction) et [serveurs minages](https://histeria.fr/wiki/worlds/serveurs-minage).
```

2023-05-01 19:34 UTC, dadodasyra commented on items/compress-cobble.md
> +-== https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/items/compress-cobble.png
nom de fichier

2023-05-01 19:34 UTC, dadodasyra commented on items/compress-cobble.md
> +| 1 lingot d'histerite |2|
moyen de pretty print ce tableau

2023-05-01 19:34 UTC, dadodasyra commented on items/drawer-upgrade.md
> +Les améliorations de boîtes de rangement permettent d'améliorer pour permettre de stocker davantage d'objets dans une même boîte.
d'améliorer quoi ?

2023-05-01 19:34 UTC, dadodasyra commented on items/drawer-upgrade.md
> +|1|1|1024|
pretty print

2023-05-01 19:34 UTC, dadodasyra commented on items/histerite-apple.md
> +La pomme en histerite est un consommable et excellent moyen de se soigner durant un combat. Il est nécessaire d'avoir atteint le niveau 25 en tueur pour pouvoir les crafter.
```suggestion
La pomme en histerite est un excellent moyen de se soigner durant un combat.
```
Les infos de craft doivent être dans #craft

2023-05-01 19:34 UTC, dadodasyra commented on items/histerite-key.md
> +| 1 diamant | 4,39|
pretty print

2023-05-01 19:34 UTC, dadodasyra commented on items/histerite-key.md
> +| 1 [Eponge puissante](https://histeria.fr/wiki/items/sponge) | 3,51|
soit tu met des majuscules partout, soit t'en met pas

2023-05-01 19:34 UTC, dadodasyra commented on items/vote-key
> +La clé de vote est obtenable en votant sur le serveur, dans tous les kit, le vote party et dans des [lucky block](https://histeria.fr/wiki/blocks/lucky-block). Vous devez l'utiliser sur les box qui s
```suggestion
La clé de vote est obtenable en votant sur le serveur, dans tous les kits, le vote party et dans des [lucky block](https://histeria.fr/wiki/blocks/lucky-block). Vous devez l'utiliser sur les box qui se trouvent dans le spawn des [serveurs minages](https://histeria.fr/wiki/worlds/monde-minage) et [serveurs factions](https://histeria.fr/wiki/worlds/serveurs-faction).
```

2023-05-01 19:34 UTC, dadodasyra commented on items/vote-key
> +|:-----------------------------------:|:------------------:|
pretty print

2023-07-11 21:55 UTC, dadodasyra commented
Poke

2023-08-30 13:36 UTC, dadodasyra requested changes

2023-08-30 13:36 UTC, dadodasyra commented on items/compresse-cobblestone.md
>  # Cobble Compresse
accent

2023-08-30 13:36 UTC, dadodasyra commented on items/drawer-upgrade.md
Nom en français

2023-08-30 13:36 UTC, dadodasyra commented on items/drawer-upgrade.md
> +Les améliorations de boîtes de rangement permettent d'améliorer les [boîtes de rangement](https://histeria.fr/wiki/blocks/drawer.md) pour permettre de stocker davantage d'objets dans une même boîte.
Pourquoi une extension de fichier sur le lien ?

2023-08-30 13:36 UTC, dadodasyra commented on items/vote-key
nom en français

2023-08-30 13:36 UTC, dadodasyra commented on items/histerite-key.md
nom en français

2023-08-30 13:36 UTC, dadodasyra commented on items/histerite-apple.md
nom en français

2023-08-31 06:41 UTC, dadodasyra requested changes
Je comprends pas pourquoi t'as tout repassé en anglais, si je met le com sur le document entier c'est prcq ça concerne le nom du fichier.

2023-08-31 06:41 UTC, dadodasyra commented on items/compresse-cobblestone.md
> +# Compresse Cobblestone
Toujours pas, à la limite Cobblestone compressé

2023-09-23 21:03 UTC, zelytra commented
@dadodasyra

2023-09-23 21:56 UTC, dadodasyra commented
On holiday until monday

2023-09-27 18:52 UTC, dadodasyra requested changes

2023-09-27 18:52 UTC, dadodasyra commented on items/compresse-cobblestone.md
"Compresse" n'existe pas dans le dictionnaire anglais

2023-09-29 15:15 UTC, dadodasyra requested changes

2023-09-29 15:15 UTC, dadodasyra commented on items/compressed-cobblestone.md
> +%%name=Cobblestone compressé%%
```suggestion
%%name=Cobblestone compressée%%
```

2023-09-29 15:15 UTC, dadodasyra commented on items/compressed-cobblestone.md
> +# Cobblestone compressé
```suggestion
# Cobblestone compressée
```

2023-10-03 08:04 UTC, zelytra commented
il faut mettre a jours ta branche @CercleTour

2023-10-05 07:14 UTC, merged