Items alaonestbien
HisteriaMC/histeria-wiki pull request #149
Opened 2023-05-01 17:23 UTC by ItamSurMc

2023-05-01 17:23 UTC, ItamSurMc commented
Issues : #36

2023-05-01 19:46 UTC, dadodasyra requested changes

2023-05-01 19:46 UTC, dadodasyra commented on items/seed-planter.md
> + ==- https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/items/shuriken.png
Ce fichier n'existe pas

2023-05-01 19:46 UTC, dadodasyra commented on items/seed-planter.md
> + ==- https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/blocks/iron_block.png
Ce fichier n'existe pas

2023-05-01 19:46 UTC, dadodasyra commented on items/seed-planter.md
> + ==- https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/items/shuriken.png
Ce fichier n'existe pas

2023-05-01 19:46 UTC, dadodasyra commented on items/seed-planter.md
> + ==- https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/items/shuriken.png
Ce fichier n'existe pas

2023-05-01 19:46 UTC, dadodasyra commented on items/seed-planter.md
> + -== https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/items/seed-planter.png
Ce fichier n'existe pas

2023-05-01 19:48 UTC, dadodasyra requested changes

2023-05-01 19:48 UTC, dadodasyra commented on items/seed-planter.md
> +Le planteur à graines est un item qui sert à planter des graines sur un rayon de 3x3 blocs. IL permet aussi de récolter les [fruits en Nocturite](https://histeria.fr/wiki/items/nocturite-fruit) sans
```suggestion
Le planteur à graines est un item qui sert à planter des graines dans un rayon de 3 blocs. Il permet aussi de récolter les [fruits de nocturite](https://histeria.fr/wiki/items/nocturite-fruit) sans avoir à casser la plantation.

```

2023-05-02 17:22 UTC, dadodasyra requested changes
J'ai un resolve le commentaire que tu avais resolve alors qu'il ne l'étais pas. De plus iron block n'a rien à faire dans items

2023-05-02 17:22 UTC, dadodasyra commented on items/seed-planter.md
> + ==- https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/blocks/iron_block.png
il existe dnas items

2023-05-02 17:22 UTC, dadodasyra commented on .assets/items/iron-block.png
rien à faire dans items

2023-05-21 10:26 UTC, dadodasyra requested changes

2023-05-21 10:26 UTC, dadodasyra commented on items/seed-planter.md
> +Le planteur à graines est un item qui sert à planter des graines dans un rayon de 3 blocs. Il permet aussi de récolter les [fruits de nocturite](https://histeria.fr/wiki/items/nocturite-fruit) sans a
Il manque les infos sur le plantage en ligne des autres graines vanilla + je suis persuadé que les loot drop de la noctu sont pas les mêmes mais sont avantagés avec le seedplanter. Et la plante ne recommence pas forcement au stade 0 mais a une chance sur 2 de recommencer au stade 1
Manque la durabilité également
```php

    public function onInteractBlock(Player $player, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector, array &$returnedItems) : ItemUseResult
    {
        if ($player instanceof CustomPlayer) {
            if (!AreaProtect::canEdit($player, $blockClicked->getPosition())) return ItemUseResult::FAIL(); //Usefull ?

            /** @var $blockClicked NetherWartPlant */
            if ($blockClicked->getTypeId() === CustomBlockTypeIds::NOCTURITE_PLANT && $blockClicked->getAge() === 3) //farm a maturation
                $this->replant($player, $blockClicked);

            if ($blockClicked->getTypeId() === CustomBlockTypeIds::FERTILIZED_DIRT || $blockClicked->getTypeId() === BlockTypeIds::FARMLAND) {
                if ($player->cooldown["seedplanter"] > time()) $this->plant($player, $blockClicked);
                else $player->cooldown["seedplanter"] = time() + 3;
            }
        }
        return ItemUseResult::NONE();
    }

    public function replant(CustomPlayer $p, Block $b)
    {
        $num = rand(1, 100);

        if ($num <= 55) $c = 2; //40% chance to get 2 seeds
        else $c = 1;


        Utils::give($p, [CustomItems::NOCTURITE_FRUIT()->setCount($c)]);

        $b->getPosition()->getWorld()->setBlock($b->getPosition(), VanillaBlocks::NETHER_WART()->setAge(mt_rand(0, 1)));
        $this->applyDamage(1);
        $job = $p->getJob(Job::MINER);
        $xp = JobAPI::getXpGivedByBlockForThisLevel($job, $job->getLevel(), CustomBlockTypeIds::NOCTURITE_PLANT);
        if (!is_null($xp)) JobAPI::addXp($p, $job, $xp);
    }

    public function plant(Player $p, Block $b): bool
    {
        if ($p instanceof CustomPlayer) {
            $inv = $p->getInventory();
            $count = 0;
            $singleLine = false;
            //Detect if one of items in array are in the player inventory return if not
            if ($b->getTypeId() === CustomBlockTypeIds::FERTILIZED_DIRT) {
                $idtoplant = CustomBlockTypeNames::NOCTURITE_PLANT;
                if (!$inv->contains(CustomBlocks::NOCTURITE_PLANT()->asItem())) return false;
            } else {
                foreach ([ItemTypeNames::WHEAT_SEEDS, ItemTypeNames::CARROT,
                             ItemTypeNames::POTATO, ItemTypeNames::PUMPKIN_SEEDS,
                             ItemTypeNames::MELON_SEEDS, ItemTypeNames::BEETROOT_SEEDS,
                             CustomBlockTypeNames::NOCTURITE_PLANT
                         ] as $seed) {
                    if ($inv->contains(StringToItemParser::getInstance()->parse($seed))) {
                        //Change signleLine to true if it's a pumpkin or melon seed
                        if (in_array($seed, [ITId::PUMPKIN_SEEDS, ITId::MELON_SEEDS])) $singleLine = true;
                        $idtoplant = $seed;
                        break;
                    }
                }

                if (!isset($idtoplant)) return false;
            }

            $pos = $b->getPosition();
            $y = $pos->getY() + 1;
            if ($singleLine) {
                $minX = $maxX = $pos->x;
                $minZ = $maxZ = $pos->z;
                $direction = Utils::getCompassDirection($p->getLocation()->getYaw());
                if ($direction === "E") {//Selon orientation pour pumpkin et pastèque, planter en rangée
                    $maxX += 9;
                } else if ($direction === "W") {
                    $minX -= 9;
                } else if ($direction === "N") {
                    $minZ -= 9;
                } else {
                    $maxZ += 9;
                }
            } else {
                $minX = $pos->x - 1;
                $maxX = $pos->x + 1;
                $minZ = $pos->z - 1;
                $maxZ = $pos->z + 1;
            }
            $blockToPlant = self::getBlockToPlant($idtoplant);
            for ($x = $minX; $x <= $maxX; $x++) {
                for ($z = $minZ; $z <= $maxZ; $z++) {
                    if (($underneath = $pos->getWorld()->getBlockAt($x, $y - 1, $z))->getTypeId() === $b->getTypeId() &&
                        $pos->getWorld()->getBlockAt($x, $y, $z)->getTypeId() === BlockTypeIds::AIR &&
                        $inv->contains(StringToItemParser::getInstance()->parse($idtoplant)->setCount($count + 1))) {
                        if ($idtoplant === CustomBlockTypeNames::NOCTURITE_PLANT && $underneath->getTypeId() !== CustomBlockTypeIds::FERTILIZED_DIRT) continue;
                        $pos->getWorld()->setBlockAt($x, $y, $z, $blockToPlant);
                        $count++;
                    }
                }
            }
            if ($count === 0) {
                $p->cooldown["seedplanter"] = time() + 2;
            } else {
                $inv->removeItem(StringToItemParser::getInstance()->parse($idtoplant)->setCount($count));
                $this->applyDamage($count);
            }
            return true;
        }
        return false;
    }

    private static function getBlockToPlant(string $id): Block
    {
        return match ($id) {
            ItemTypeNames::WHEAT_SEEDS => VanillaBlocks::WHEAT(),
            ItemTypeNames::PUMPKIN_SEEDS, => VanillaBlocks::PUMPKIN_STEM(),
            ItemTypeNames::MELON_SEEDS => VanillaBlocks::MELON_STEM(),
            ItemTypeNames::BEETROOT_SEEDS => VanillaBlocks::BEETROOTS(),
            CustomBlockTypeNames::NOCTURITE_PLANT => CustomBlocks::NOCTURITE_PLANT(),
            ItemTypeNames::CARROT => VanillaBlocks::CARROTS(),
            ItemTypeNames::POTATO => VanillaBlocks::POTATOES(),
            default => 0
        };
    }
```

2023-09-16 09:29 UTC, closed without merging