Speed Stick
HisteriaMC/histeria-wiki pull request #150
Opened 2023-05-01 19:33 UTC by VIP3R1279

Ajout #43

2023-05-01 19:52 UTC, dadodasyra requested changes

2023-05-01 19:52 UTC, dadodasyra commented on items/speed-stick.md
> +Le bâton de vitesse est l'un des trois bâtons à effet sur le serveur avec le bâton de saut et le bâton de soin. Vous pouvez en obtenir en utilisant des clés de vote mais surtout en les craftant dans
rajouter les liens de redirection vers les autres bâtons même si ils ne sont pas encore rédigés
ainsi que
```suggestion
Le bâton de vitesse est l'un des trois bâtons à effet sur le serveur avec le bâton de saut et le bâton de soin. Vous pouvez en obtenir en utilisant des clés de vote mais également en les craftant dans une table de craft.
```

Les niveaux de craft doivent se trouver dans la section craft

2023-05-01 19:52 UTC, dadodasyra commented on items/speed-stick.md
> +Lorsque vous utilisez ce bâton, cela vous donnera l'effet de vitesse de niveau 2 pour 15 secondes. Il y a un cooldown de 15 secondes entre chaque utilisation.
```suggestion
Lorsque vous utilisez ce bâton, il vous donnera l'effet de vitesse de niveau 2 pendant 15 secondes. Il y a un cooldown de 15 secondes entre chaque utilisation.
```
qu'est ce que vous avez tous avez votre "pour", pour c'est pour une raison

2023-05-01 21:10 UTC, dadodasyra commented
Quand une PR ne contient pas tout le contenu final il faut la mettre en "draft" (pour brouillon). Sinon tu te retrouves avec une review alors que tu n'as pas fini et je dois tout relire de 0

2023-05-01 21:17 UTC, dadodasyra requested changes
Si je me trompe pas par ailleurs les sticks sont obtenables dans des lucky block

J'ai remarqué que tu n'as pas utilisé le même format pour la table de craft, l'une a de l'indentation les autres non, merci de se réferer à la doc officielle sur le site pour son bon usage.

_En dehors de tout ça, c'est une bonne première PR, demande Itam et les autres ils ont bien fait de la merde sur leurs premières_

PS: Je sais pas si Cercle t'as dit mais tu peux accepter les suggestions en dessous en utilisant le bouton commit ou add suggestion to batch. Par contre si tu le fais il faudra après que tu resynchronises en utilisant pull ou update sur ton git local.

2023-05-01 21:17 UTC, dadodasyra commented on items/heal-stick.md
> +Le bâton de guerrier ou bâton de guerrier est l'un des trois bâtons à effet sur le serveur avec le [bâton de saut](https://histeria.fr/wiki/items/jump-stick) et le [bâton de vitesse](https://histeria
> Le bâton de guerrier ou bâton de guerrier
???

même remarque que le speed stick, également en les craftant, pas "surtout", ça voudrait dire que tu minimise le vote.

2023-05-01 21:17 UTC, dadodasyra commented on items/speed-stick.md
> +Le bâton de vitesse est l'un des trois bâtons à effet sur le serveur avec le [bâton de saut](https://histeria.fr/wiki/items/jump-stick) et le [bâton de guerrier](https://histeria.fr/wiki/items/heal-s
Je préfère "bâton de soin" à guerrier

2023-05-01 21:17 UTC, dadodasyra commented on items/jump-stick.md
> +Lorsque vous utilisez ce bâton, il vous donnera l'effet de saut amélioré qui vous permet de sauter à 9 blocks de haut pendant 10 secondes. Il y a un cooldawn de 60 secondes entre chaque utilisation.
```suggestion
Lorsque vous utilisez ce bâton, il vous donnera l'effet de saut amélioré qui vous permet de sauter à 9 blocs de haut pendant 10 secondes. Il y a un cooldown de 60 secondes entre chaque utilisation.
```

2023-05-01 21:17 UTC, dadodasyra commented on items/jump-stick.md
> +Le bâton de saut est l'un des trois bâtons à effet sur le serveur avec le [bâton de vitesse](https://histeria.fr/wiki/items/speed-stick) et le [bâton de guerrier](https://histeria.fr/wiki/items/heal-
```suggestion
Le bâton de saut est l'un des trois bâtons à effet sur le serveur avec le [bâton de vitesse](https://histeria.fr/wiki/items/speed-stick) et le [bâton de soin](https://histeria.fr/wiki/items/heal-stick). Vous pouvez en obtenir en utilisant des clés de vote mais également en les craftant dans une table de craft.
```

2023-05-01 21:17 UTC, dadodasyra commented on items/speed-stick.md
> +Le bâton de vitesse est l'un des trois bâtons à effet sur le serveur avec le [bâton de saut](https://histeria.fr/wiki/items/jump-stick) et le [bâton de guerrier](https://histeria.fr/wiki/items/heal-s
```suggestion
Le bâton de vitesse est l'un des trois bâtons à effet sur le serveur avec le [bâton de saut](https://histeria.fr/wiki/items/jump-stick) et le [bâton de soin](https://histeria.fr/wiki/items/heal-stick). Vous pouvez en obtenir en utilisant des clés de vote mais surtout en les craftant dans une table de craft. 
```

2023-05-01 21:17 UTC, dadodasyra commented on items/heal-stick.md
> +Le bâton de guerrier ou bâton de guerrier est l'un des trois bâtons à effet sur le serveur avec le [bâton de saut](https://histeria.fr/wiki/items/jump-stick) et le [bâton de vitesse](https://histeria
```suggestion
Le bâton de soin ou bâton de guerrier est l'un des trois bâtons à effet sur le serveur avec le [bâton de saut](https://histeria.fr/wiki/items/jump-stick) et le [bâton de vitesse](https://histeria.fr/wiki/items/speed-stick). Vous pouvez en obtenir en utilisant des clés de vote mais surtout en les craftant dans une table de craft.
```

2023-05-02 16:53 UTC, VIP3R1279 commented
J'ai effectué les modif demande de #42 #43 et #41

2023-05-02 17:18 UTC, dadodasyra commented
Dans ce cas là tu dois aller sur moi partout ou tu vois que ça parle de review et tu fais "re request review"

2023-05-02 17:19 UTC, dadodasyra requested changes

2023-05-02 17:19 UTC, dadodasyra commented on items/jump-stick.md
> + -==
pas de résultat de craft ?

2023-05-03 19:32 UTC, VIP3R1279 commented
ajout #34 #33 #31

2023-05-05 08:43 UTC, dadodasyra requested changes
Pour les icon= je sais pas si il les faut ou pas je connais le format

2023-05-05 08:43 UTC, dadodasyra commented on items/banknote.md
> +/bank [montant]
<montant>, l'argument est obligatoire donc <>. Sinon il faudrait la mettre peut être dans un format bloc de code

2023-05-05 08:43 UTC, dadodasyra commented on items/lottery-ticket.md
> +Le ticket de lotterie est une aide économique pour les joueurs. Elle s'obtient dans le kit du [grade Omega](https://histeria.fr/shop), ils peuvent s'acheter dans la [boutique](https://histeria.fr/sho
```suggestion
Le ticket de lotterie est une aide économique pour les joueurs. Elle s'obtient dans le kit du [grade Omega](https://histeria.fr/shop), ils peuvent s'acheter dans la [boutique](https://histeria.fr/shop), dans les [lucky blocks](https://histeria.fr/wiki/blocks/lucky-block), en [votant](http://vote.histeria.fr/), dans le calendrier de vote, dans plusieurs niveaux des différents métiers et dans les boxs.
```

2023-05-05 08:43 UTC, dadodasyra commented on items/lottery-ticket.md
> +Le ticket de lotterie est une aide économique pour les joueurs. Elle s'obtient dans le kit du [grade Omega](https://histeria.fr/shop), ils peuvent s'acheter dans la [boutique](https://histeria.fr/sho
A verif, pas de lien pour le calendrier de vote ? pour les jobs et les boxs ?

2023-05-05 08:43 UTC, dadodasyra commented on items/lottery-ticket.md
> +| 1% | 1 Millions $ |
Tout est écrit numériquement, alors autant l'écrire en numérique ici aussi

2023-05-05 08:43 UTC, dadodasyra commented on items/lottery-ticket.md
> +|:------------:|---------|
Pretty print le tableau (cf google)

2023-05-05 08:43 UTC, dadodasyra commented on items/lottery-ticket.md
> +| Probabilité (%) | Montant |
Soit on indique pas (%) dans Probabilité puisqu'il est déjà dans le tableau, soit on l'enlève du tableau

2023-05-05 08:43 UTC, dadodasyra commented on items/shuriken.md
> +Le shuriken est un projectile fait à base d'histerite et de fer. On l'obtient en le fabriquant, dans les boxs et dans les kits [Omega, Interplanétaire et](https://histeria.fr/shop) et créateur de con
y a deux "et"

2023-05-05 08:43 UTC, dadodasyra commented on items/shuriken.md
> +Le shuriken est un projectile qui se lance sur les ennemies. Ce dernier est utilisé afin d'éviter à l'ennemie de fuir le combat.
les ennemis sont tous des femmes ? (2x btw)

2023-05-05 08:43 UTC, dadodasyra commented on items/jump-stick.md
> +%%https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/items/jump-stick.png%%
y a pas un icon= ?

2023-05-05 08:43 UTC, dadodasyra commented on items/heal-stick.md
> +%%https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/items/heal-stick.png%%
icon= ?

2023-05-05 08:43 UTC, dadodasyra commented on items/banknote.md
> +%%icon=https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/items/banknote.png%%
icon= ?

2023-05-13 10:14 UTC, VIP3R1279 commented on items/lottery-ticket.md
> +Le ticket de lotterie est une aide économique pour les joueurs. Elle s'obtient dans le kit du [grade Omega](https://histeria.fr/shop), ils peuvent s'acheter dans la [boutique](https://histeria.fr/sho
sur le wiki, il n'y en a pas et j'ai regarder les issues qu'il reste à faire mais aucune du calendrier vote jobs et boxs

2023-05-13 10:24 UTC, dadodasyra commented on items/lottery-ticket.md
> +Le ticket de lotterie est une aide économique pour les joueurs. Elle s'obtient dans le kit du [grade Omega](https://histeria.fr/shop), ils peuvent s'acheter dans la [boutique](https://histeria.fr/sho
mh ça me semble assez difficile à preshot, laisse le comme c'est actuellement

2023-05-13 10:24 UTC, dadodasyra commented on items/lottery-ticket.md
> +Le ticket de lotterie est une aide économique pour les joueurs. Elle s'obtient dans le kit du [grade Omega](https://histeria.fr/shop), ils peuvent s'acheter dans la [boutique](https://histeria.fr/sho
Si y a pas d'issue pour, tu peux les créer, on en a oublié

2023-05-15 15:02 UTC, zelytra approved these changes
@dadodasyra

2023-05-15 20:18 UTC, dadodasyra requested changes

2023-05-15 20:18 UTC, dadodasyra commented on items/banknote.md
> +/bank [<montant>]
à voir en preview, aller à la ligne ne sert à rien en markdown par rapport au résultat + on a demandé à ce que ce soit en bloc de code et le montant ne peut pas être à la fois optionnel et obligatoire

2023-05-15 20:18 UTC, dadodasyra commented on items/banknote.md
> +Pour recevoir le chèque, il faut seulement faire un clic droit sur le chèque en main.
"seulement" mal formulé, tout simplement à la limite, mais pour nos utilisateurs mobiles ça n'a aucun sens

2023-05-15 20:18 UTC, dadodasyra commented on items/jump-stick.md
> +Le bâton de saut est l'un des trois bâtons à effet sur le serveur avec le [bâton de vitesse](https://histeria.fr/wiki/items/speed-stick) et le [bâton de soin](https://histeria.fr/wiki/items/heal-stic
Il me semble l'avoir déjà dit.. "les craftant dans une table de craft.", répétitif

2023-05-15 20:18 UTC, dadodasyra commented on items/heal-stick.md
> +Le bâton de soin est l'un des trois bâtons à effet sur le serveur avec le [bâton de saut](https://histeria.fr/wiki/items/jump-stick) et le [bâton de vitesse](https://histeria.fr/wiki/items/speed-stic
Il me semble l'avoir déjà dit.. "les craftant dans une table de craft.", répétitif

2023-05-15 20:18 UTC, dadodasyra commented on items/lottery-ticket.md
> +Le ticket de lotterie, une fois utilisé est un évènement économique qui vous donnera entre 5 000$ pour les moins chanceux jusqu'à 1 millions pour les plus chanceux. Il n'est utilisable qu'une seule f
1 million c'est forcément singulier
```suggestion
Le ticket de lotterie, une fois utilisé est un évènement économique qui vous donnera entre 5 000$ pour les moins chanceux jusqu'à 1 million pour les plus chanceux. Il n'est utilisable qu'une seule fois.
```

2023-05-15 20:18 UTC, dadodasyra commented on items/lottery-ticket.md
> +| 23%             |25 000$      |
```suggestion
| 23%             | 25 000$     |
```

2023-05-15 20:18 UTC, dadodasyra commented on items/shuriken.md
> +Le shuriken est un projectile qui se lance sur les ennemis. Ce dernier est utilisé afin d'éviter à l'ennemie de fuir le combat.
les ennemis ne sont pas uniquement des femmes..

2023-05-15 20:18 UTC, dadodasyra commented on items/speed-stick.md
> +Le bâton de vitesse est l'un des trois bâtons à effet sur le serveur avec le [bâton de saut](https://histeria.fr/wiki/items/jump-stick) et le [bâton de soin](https://histeria.fr/wiki/items/heal-stick
Il me semble l'avoir déjà dit.. "les craftant dans une table de craft.", répétitif

2023-05-15 20:19 UTC, dadodasyra commented on items/shuriken.md
> +Le shuriken est un projectile qui se lance sur les ennemies. Ce dernier est utilisé afin d'éviter à l'ennemie de fuir le combat.
https://github.com/HisteriaMC/histeria-wiki/pull/150#discussion_r1185835704

2023-05-15 20:19 UTC, dadodasyra commented on items/shuriken.md
> +Le shuriken est un projectile qui se lance sur les ennemis. Ce dernier est utilisé afin d'éviter à l'ennemie de fuir le combat.
https://github.com/HisteriaMC/histeria-wiki/pull/150#discussion_r1185835704

2023-07-11 21:55 UTC, dadodasyra commented
Poke

2023-07-24 23:05 UTC, zelytra approved these changes

2023-08-08 16:11 UTC, dadodasyra approved these changes

2023-08-08 17:35 UTC, merged