Items VIP3R
HisteriaMC/histeria-wiki pull request #159
Opened 2023-05-13 21:30 UTC by ItamSurMc

#38 #30 #29 #27

2023-05-13 21:35 UTC, dadodasyra commented
Mais pourquoi viper fait pas sa propre pr ?

2023-05-13 21:37 UTC, ItamSurMc commented
dado c'était avnt qu'il sache faire, j'avais fais une pr et elle a était close pour je ne sais quelle raison. Je viens de le voir et donc je la refait

2023-05-13 22:59 UTC, dadodasyra commented
![image](https://github.com/HisteriaMC/histeria-wiki/assets/44753923/e0997887-38dc-4e2c-bc92-49065a34fa73)
c'est clairement toi qui l'a close, je vois pas pourquoi tu l'as pas réouverte

2023-05-15 15:07 UTC, zelytra requested changes

2023-05-15 15:07 UTC, zelytra commented on items/hang-glider.md
> + ==-
```suggestion
 ==- 

```

2023-05-15 20:28 UTC, dadodasyra requested changes

2023-05-15 20:28 UTC, dadodasyra commented on blocks/histerite-block.md
> +Le bloc d'Histerite est la condensation de 9 [lingots d'Histerite](https://histeria.fr/wiki/items/histerite-ingot).
![image](https://github.com/HisteriaMC/histeria-wiki/assets/44753923/50a36017-e068-409e-bff4-7538dec5a5e2)
aucun rapport

2023-05-15 20:28 UTC, dadodasyra commented on blocks/histerite-block.md
> +Le bloc d'Histerite est la condensation de 9 [lingots d'Histerite](https://histeria.fr/wiki/items/histerite-ingot).
ah quoi que, ok ça pourrait passer mais bon

2023-05-15 20:28 UTC, dadodasyra commented on items/chest-finder.md
> +L'unclaim Finder est utile pour trouver des bases à piller. Ce dernier donne le nombre de coffre(s) dans un certains rayon.
si on fait une page wiki dessus c'est pour donner des détails utiles, donc on indique la distance

2023-05-15 20:28 UTC, dadodasyra commented on items/chest-finder.md
> +L'unclaim Finder est utile pour trouver des bases à piller. Ce dernier donne le nombre de coffre(s) dans un certains rayon.
```php
    public function onRun(): void
    {
        $player = $this->player;
        if (!$this->player->isOnline() || $player->getInventory()->getItemInHand()->getTypeId() !== CustomItemTypeIds::CHEST_FINDER) {
            unset(ChestFinder::$listPlayers[$player->getName()]);
            $this->getHandler()->cancel();
            return;
        }

        $chunks = $this->getChunks($player);

        $count = 0;
        if (!isset($chunks)) return;

        foreach ($chunks as $chunk) {
            /** @var $chunk Chunk */
            if ($chunk instanceof Chunk) {
                foreach ($chunk->getTiles() as $tile) {
                    if ($tile instanceof Chest
                        || $tile instanceof TrappedChest
                        || $tile instanceof DrawerTile
                        || $tile instanceof Furnace
                        || $tile instanceof ItemFrame
                        || $tile instanceof Hopper
                        || $tile instanceof ShulkerBox
                        || $tile instanceof Barrel) {
                        $count++;
                    }
                }
            }
        }
        if ($count === 0) $num = "§eIl n'y a §baucun"; else $num = "§eIl y'a §b" . $count;
        $player->sendPopup($num . " §ecoffre(s) aux alentours");
    }

    public function getChunks(Player $player): array
    {
        $chunks = [];

        $level = $player->getWorld();
        $pos = $player->getPosition();

        $baseX = $pos->getFloorX() >> Chunk::COORD_BIT_SIZE; //Get chunk x & z
        $baseZ = $pos->getFloorZ() >> Chunk::COORD_BIT_SIZE;

        for ($x = -3; $x <= 3; $x++) {
            for ($z = -3; $z <= 3; $z++) {
                $chunks[] = $level->getChunk($x + $baseX, $z + $baseZ);
            }
        }

        return $chunks;
    }
```

2023-05-15 20:28 UTC, dadodasyra commented on items/chest-finder.md
Il n'y a pas que les coffres

2023-05-15 20:28 UTC, dadodasyra commented on items/chest-finder.md
> +L'unclaim finder s'obtient en le craftant ou dans les box, il est disponible au /shop.
```suggestion
L'unclaim finder s'obtient dans les box ou en le craftant, il est également disponible au /shop.

```

2023-05-15 20:28 UTC, dadodasyra commented on items/chest-finder.md
> +La zone qu'il détecte est de 128 blocs par 128 blocs. Ce dernier ne peut pas casser.
Factuellement faux, pas baser sur le nombre de block

2023-05-15 20:28 UTC, dadodasyra commented on items/dynamite.md
> +Les dynamites s'obtiennent grâce au craft, à l'intérieur des box et des lucky blocks.
grâce au craft me semble maladroit

2023-05-15 20:28 UTC, dadodasyra commented on items/dynamite.md
> +La dynamite est utile pour faire une petite explosion afin de pénétrer à l'interieur du base protéger par des claims.
```suggestion
La dynamite est utile pour faire une petite explosion afin de pénétrer à l'intérieur du base protéger par des claims.

```

2023-05-15 20:28 UTC, dadodasyra commented on items/hang-glider.md
> +Le planeur peut s'obtenir en le fabriquant en utilisant une table de craft.
```suggestion
Le planeur peut s'obtenir en le fabriquant dans une table de craft.

```

2023-05-15 20:28 UTC, dadodasyra commented on items/hang-glider.md
> +Il fait planer le joueur qui l'a en main et annule tout dégats de chutes.
```suggestion
Il fait planer le joueur qui l'a en main et annule tout dégat de chutes.

```

2023-07-11 21:55 UTC, dadodasyra commented
Poke

2023-09-16 09:28 UTC, closed without merging