Changement des textures
HisteriaMC/histeria-wiki pull request #160
Opened 2023-08-12 08:32 UTC by ItamSurMc

2023-08-12 18:01 UTC, dadodasyra requested changes

2023-08-12 18:01 UTC, dadodasyra commented on .assets/items/forge-note.png
laisse l'ancienne, ça changera

2023-08-12 18:01 UTC, dadodasyra commented on .assets/items/hammer.png
laisse l'ancienne

2023-08-12 18:01 UTC, dadodasyra commented on .assets/items/killtag.png
l'ancien fichier s'appelait kill-tag

2023-08-12 18:19 UTC, dadodasyra requested changes

2023-08-12 18:19 UTC, dadodasyra commented on .assets/armors/nocturit-boots.png
nocturite-boots

2023-08-12 18:19 UTC, dadodasyra commented on .assets/blocks/lucky-block.png
New texture

2023-08-12 18:19 UTC, dadodasyra commented on .assets/blocks/nocturite-crystal.png
il a dépop ?

2023-08-12 18:26 UTC, dadodasyra approved these changes

2023-08-13 10:09 UTC, zelytra requested changes

2023-08-13 10:10 UTC, zelytra commented
Certaines textures on bien eu besoins de ce changement, mais pour 90% des autres changement ce sont les même textures mais en moins bien fait, ça n'as aucun sens

2023-08-13 10:12 UTC, HARYA301 commented
Pourquoi Itam tu as push les nouvelles texture?? Je te rappelle que certains peuvent encore changer en fonction de l'avis d'Ailfe ou Dado...

2023-08-13 10:13 UTC, zelytra commented
> Pourquoi Itam tu as push les nouvelles texture?? Je te rappelle que certains peuvent encore changer en fonction de l'avis d'Ailfe ou Dado...

Dado à approuvé la PR donc techniquement il est d'accord

2023-08-13 10:14 UTC, HARYA301 commented
> > Pourquoi Itam tu as push les nouvelles texture?? Je te rappelle que certains peuvent encore changer en fonction de l'avis d'Ailfe ou Dado...
> 
> Dado à approuvé la PR donc techniquement il est d'accord

Étrange alors, surtout que plus haut il dit qu'il ne fallait pas changer certains car elles vont recevoir des changements
Peu importe

2023-08-13 10:17 UTC, zelytra commented
> > > Pourquoi Itam tu as push les nouvelles texture?? Je te rappelle que certains peuvent encore changer en fonction de l'avis d'Ailfe ou Dado...
> > 
> > 
> > Dado à approuvé la PR donc techniquement il est d'accord
> 
> Étrange alors, surtout que plus haut il dit qu'il ne fallait pas changer certains car elles vont recevoir des changements Peu importe

De toute façon cette PR est poussé sur la branche v6.5 et pourras être encore modifié pour plus tard. Mais ca serais mieux de poussé uniquement les textures dont vous êtes sûr

2023-08-13 12:34 UTC, ItamSurMc commented on .assets/blocks/histerite-anvil.png
en français ?

2023-08-13 12:36 UTC, zelytra commented on .assets/blocks/histerite-anvil.png
https://fr.wiktionary.org/wiki/croper

2023-09-22 17:50 UTC, closed without merging