Réécriture en français
HisteriaMC/histeria-wiki pull request #162
Opened 2023-08-13 20:24 UTC by ItamSurMc

#151

2023-08-13 20:27 UTC, ItamSurMc commented
J'avoue ne pas comprendre pourquoi ca un check a fail

2023-08-13 23:24 UTC, zelytra commented
> J'avoue ne pas comprendre pourquoi un check a fail

Bah regarde ce qui est écrit dans l'exécution de la pipeline et tu comprendra

2023-08-14 18:40 UTC, zelytra commented
@dadodasyra Grosse relecture nécessaire soit attentif

2023-08-14 18:43 UTC, dadodasyra commented
holy shit

2023-08-14 19:10 UTC, dadodasyra requested changes
Les liens dans la documentation n'ont pas été modifiés malgré le changement de chemin
Il faut le faire à la masse avec des Ctrl Shift R. Les paths d'image et lien de redirections

Tant que t'y es à changer tout les titres, dégage les "Les" devant, ça n'a aucun sens (les commandes..)

2023-08-14 19:10 UTC, dadodasyra commented on commandes/commandes-des-gradés.md
> +# Les commandes gradées
match title

2023-08-14 19:10 UTC, dadodasyra commented on développeur/bien-pratiquer-le-wiki.md
> +# Guide de bonne pratique
match file title

2023-08-14 19:10 UTC, dadodasyra commented on développeur/bien-pratiquer-le-wiki.md
ça veut rien dire bien pratiquer le wiki

2023-08-14 19:10 UTC, dadodasyra commented on objets/baton-de-rapidité.md
> +# Bâton de vitesse
match title

2023-08-14 19:10 UTC, dadodasyra commented on objets/baton-de-saut.md
> + ==- https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/items/histerite-stick.png
normalement on fait pas 2 choses différentes dans la meme pr, en plus ce changement n'avait strictement aucune utilité. C'est encore moins esthétique qu'avant

2023-08-14 19:10 UTC, dadodasyra commented on objets/baton-de-soin.md
> + ==- https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/items/histerite-stick.png
Pareil normalement ça n'a rien à voir avec cette pr

2023-08-14 19:10 UTC, dadodasyra commented on objets/forge-note.md
pas traduit

2023-08-14 19:10 UTC, dadodasyra commented on outils/hache-en-histerite.md
> + ==- https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/items/histerite-ingot.png
toujours aucune raison de faire ça, mauvaise gestion des conflits

2023-08-14 19:10 UTC, dadodasyra commented on objets/baton-de-soin.md
> + ==- https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/items/histerite-stick.png
mauvaise gestion des conflits

2023-08-14 19:10 UTC, dadodasyra commented on outils/houe-en-histerite.md
> + ==- https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/items/histerite-ingot.png
toujours aucune raison de faire ça, mauvaise gestion des conflits

2023-08-14 19:10 UTC, dadodasyra commented on outils/pelle-en-histerite.md
> + -== https://raw.githubusercontent.com/ItamSurMc/histeria-wiki/main/.assets/items/histerite-shovel.png
toujours aucune raison de faire ça, mauvaise gestion des conflits

2023-09-15 21:51 UTC, ItamSurMc commented on objets/baton-de-saut.md
> + ==- https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/items/histerite-stick.png
c'est fait comme c'est dans la table de craft 
![image](https://github.com/HisteriaMC/histeria-wiki/assets/96440284/de1a8f10-0641-44f4-b646-e46ce97663d8)

2023-09-15 21:56 UTC, ItamSurMc commented
> Les liens dans la documentation n'ont pas été modifiés malgré le changement de chemin Il faut le faire à la masse avec des Ctrl Shift R. Les paths d'image et lien de redirections
> 
> Tant que t'y es à changer tout les titres, dégage les "Les" devant, ça n'a aucun sens (les commandes..)

2023-09-15 21:58 UTC, ItamSurMc commented
@dadodasyra

2023-09-15 22:06 UTC, dadodasyra approved these changes
J'espère n'avoir rien rater.. ça risque de péter pas mal de truc

2023-09-15 22:09 UTC, ItamSurMc commented
@zelytra il ne manque que toi 
(j'espère que ca ne va rien casser)

2023-09-19 11:55 UTC, zelytra approved these changes

2023-09-19 11:56 UTC, merged