Patch coffre arene
HisteriaMC/histeria-wiki pull request #216
Opened 2023-12-07 16:56 UTC by Tonmou8128

Fix #213 

J'ai rédigé la page du coffre d'arène, je l'ai mis dans la catégorie mondes, je me disait que ça conviendrait mieux que blocs.

2023-12-08 10:35 UTC, dadodasyra requested changes
Pourquoi l'usage de `<br>` ? autant aller à la ligne ?

Je me demande surtout si le plus simple ne serait pas de mettre sous forme de screen du contenu des coffres d'arènes au lieu du texte. Après ça veut aussi dire pas de redirection.. sujet à débat

2023-12-08 10:37 UTC, Tonmou8128 commented on mondes/arena-chest.md
> +- - 8 [shirikens](https://histeria.fr/wiki/objets/shuriken)
Faute de frappe

2023-12-08 10:38 UTC, Tonmou8128 commented
> Pourquoi l'usage de `<br>` ? autant aller à la ligne ?
> 
> Je me demande surtout si le plus simple ne serait pas de mettre sous forme de screen du contenu des coffres d'arènes au lieu du texte. Après ça veut aussi dire pas de redirection.. sujet à débat

À la ligne il n'y avait pas d'espace entre chaque loot possible
Je peux screen aussi, si tu préfères

2023-12-13 13:00 UTC, dadodasyra approved these changes

2023-12-13 15:16 UTC, merged