Rendu 3D des blocks
HisteriaMC/histeria-wiki pull request #227
Opened 2023-12-16 16:16 UTC by HARYA301

#174

![image](https://github.com/HisteriaMC/histeria-wiki/assets/57374230/b891efeb-f89d-40c0-b235-3472c3345976)

2023-12-16 16:24 UTC, Zirowz commented
@Tonmou8128 ducoup tu peux déjà commencer à mettre à jour avec le coffre d'arène.

2023-12-16 16:28 UTC, Tonmou8128 commented
> @Tonmou8128 ducoup tu peux déjà commencer à mettre à jour avec le coffre d'arène.

Autant faire tout d'un coup

2023-12-18 07:57 UTC, zelytra commented
Toutes les images sont mal cadré, retirer l'espace vide

2023-12-18 14:34 UTC, HARYA301 commented
> Toutes les images sont mal cadré, retirer l'espace vide

ça ne va pas crée des problèmes de rendu? (Question sérieuse, je ne sais pas comment ça fonctionne)

2023-12-19 10:02 UTC, dadodasyra requested changes
Chest et chest front, il faut enlever chest front et le modifier dans le "code"

2023-12-19 10:20 UTC, Tonmou8128 commented
> Chest et chest front, il faut enlever chest front et le modifier dans le "code"

C'est dans #213 si je me trompe pas

2024-01-09 18:05 UTC, ItamSurMc commented
@HARYA301 tu as fais les modifs demandées ?

2024-01-10 07:34 UTC, dadodasyra commented
Faut resolve les conflicts et faire le contenu de la review @HARYA301

2024-01-11 21:52 UTC, HARYA301 commented
Il y a juste le conflit à resolve de souvenir

2024-01-11 21:54 UTC, HARYA301 commented
Erreur de ma part, j'ai oublié d'enlever les espaces dans les icones

2024-01-11 21:59 UTC, HARYA301 commented
C'est bon c'est à vous de faire

2024-01-11 22:00 UTC, HARYA301 commented
@ItamSurMc

2024-01-12 08:21 UTC, dadodasyra approved these changes

2024-01-12 15:16 UTC, zelytra requested changes
Les images ne sont pas carré

2024-01-12 16:29 UTC, HARYA301 commented
> Les images ne sont pas carré

c'est fait

2024-01-12 17:55 UTC, zelytra approved these changes

2024-01-12 17:55 UTC, merged