Correction-fautes-noms
HisteriaMC/histeria-wiki pull request #230
Opened 2023-12-18 13:36 UTC by SwouitAzia

Corrections des fautes dans quasiment tous les fichiers .md

Close #226

2023-12-19 08:04 UTC, zelytra commented
@dadodasyra @ItamSurMc J'impose une double relecture sur cette MR. Heavy task

2023-12-19 09:48 UTC, dadodasyra requested changes
J'ai arrêté à un moment avec les # Obtention prcq y en avait trop, mais c'est partout la meme histoire
J'ai pas trop compris cette obstination au vanilla en majuscule aussi mais bon

2023-12-19 09:48 UTC, dadodasyra commented on armures/nocturite-chestplate.md
> +## Obtention
pas compris ça, ça fait partie du craft, c'est une permission nécessaire

2023-12-19 09:48 UTC, dadodasyra commented on armures/nocturite-helmet.md
> +## Obtention
pas compris ça, ça fait partie du craft, c'est une permission nécessaire

2023-12-19 09:48 UTC, dadodasyra commented on armures/nocturite-helmet.md
>  Pour pouvoir le favriquer, vous devez être niveau 30 dans le métier d'agriculteur.
favriquer, profite en pour fix

2023-12-19 09:48 UTC, dadodasyra commented on blocs/histerite-anvil.md
> +L'enclume en Histerite est une enclume moddée présente sur le serveur. Elle se trouve aux spawns des [serveurs factions](https://histeria.fr/wiki/mondes/serveurs-faction), mais elle n'est ni obtenabl
"L'enclum eest une enclume" à reformuler

2023-12-19 09:48 UTC, dadodasyra commented on blocs/histerite-block.md
> +Le bloc en Histerite est le regroupement de 9 [lingots d'Histerite](https://histeria.fr/wiki/objets/histerite).
bloc de diamant, pas bloc en diamant.. je vois pas pourquoi on devrait passer à en
C'est le cas un peu partout ici

2023-12-19 09:48 UTC, dadodasyra commented on blocs/histerite-block.md
> +Il est également très utilisé pour un grand nombre de crafts comme la [terre fertilisée](https://histeria.fr/wiki/blocs/fertilized-dirt), le coffre en Histerite, l'obsidienne renforcé et bien plus en
"est également" après avoir rien dit ?

2023-12-19 09:48 UTC, dadodasyra commented on blocs/histerite-block.md
> +Il est également très utilisé pour un grand nombre de crafts comme la [terre fertilisée](https://histeria.fr/wiki/blocs/fertilized-dirt), le coffre en Histerite, l'obsidienne renforcé et bien plus en
pas de page sur l'obsidian renforcé et le coffre en hist ?

2023-12-19 09:48 UTC, dadodasyra commented on blocs/lucky-block.md
> +Le Lucky Block est des blocs qui, une fois cassé, déclenche un événement aléatoire positif ou négatif. Vous pouvez en obtenir en minant des [minerais aléatoires](https://histeria.fr/wiki/blocs/lucky-
"est des blocks"

2023-12-19 09:48 UTC, dadodasyra commented on blocs/lucky-block.md
> +| punching ball |1.12|                     Fait apparaître une [Boule de frappe](https://histeria.fr/wiki/objets/punching-ball)                               |
boule de frappe ??? wtf ??

2023-12-19 09:48 UTC, dadodasyra commented on blocs/nocturite-block.md
> +%%name=Bloc en Nocturite%%
même remarque que bloc "en" histerite. on dit bloc de diamant, pas bloc en diamant

2023-12-19 09:48 UTC, dadodasyra commented on blocs/poison-obsidian.md
> +L'obsidienne empoisonnée est une variante de l'obsidienne reconnaissable avec ses filaments verts qui la parcourent. Une fois cette obsidienne cassée, le joueur obtient un effet de Poison III pour un
c'est que pour les bases cliams les casseurs d'obsi, c'est cassable à la main sinon

2023-12-19 09:48 UTC, dadodasyra commented on blocs/reinforced-obsidian.md
> +L'obsidienne renforcée est une variante de l'obsidienne reconnaissable avec ses filaments rouges qui la parcourent. L'obsidienne renforcée est plus résistante que l'obsidienne classique. Pour la cass
on dit fils de pute, pas fils à pute

2023-12-19 09:48 UTC, dadodasyra commented on blocs/reinforced-obsidian.md
> +Cette obsidienne est très pratique pour protéger vos bases grâce à sa résistance générale. Elle peut également être utilisée pour fabriquer le casseur à obsidienne.
pourquoi enlever l'hyperlink de l'obsi breaker + pareil, fils de pute pas fils à pute

2023-12-19 09:48 UTC, dadodasyra commented on blocs/spike.md
> +# Epine
Archaisme littéraire peu usité.

Je pense que compte tenu du block on peut faire comme les lucky block et ne pas le traduire, parce que très franchement "epine" c'est vraiment moche

2023-12-19 09:48 UTC, dadodasyra commented on blocs/spike.md
> +Elle permet d'ajouter une défense supplémentaire dans vos bases et infligent des dégâts au contact. Très utile contre les envahisseurs !
on a encore la marque du pluriel à infligent

2023-12-19 09:48 UTC, dadodasyra commented on boss/fonctionnement-des-boss.md
> +Le Colisée, accessible via la commande __/boss__ en jeu, vous permet d'accéder au lieu de combat contre les boss. Le PvP y est __désactivé__ mais __vous pouvez y perdre votre stuff__.
JE vois pas trop en Quoi C'est un Nom Propre Colisée

2023-12-19 09:48 UTC, dadodasyra commented on boss/hermes.md
> +  - Les sandales d'Hermes possèdent l'enchantement unique [__Reset__](https://histeria.zelytra.fr/wiki/enchants/reset) qui permet, lorsqu'il est activé, de réinitialiser tout vos temps de recharge ac
"tous vos" il me semble, à verif

2023-12-19 09:48 UTC, dadodasyra commented on commandes/home-and-tp-commands.md
> +|`/boss`|Se téléporter au Colisée des boss|
nom propre ?

2023-12-19 09:48 UTC, dadodasyra commented on enchantements/compressor.md
> +L'enchantement Compressor est fusionnable avec une [pioche](https://histeria.fr/wiki/outils/histerite-pickaxe). Quand le porteur mine de la pierre, cette pierre s'auto-craft en [pierre taillée compre
archaisme littéraire.
Gardons cobblestone qui est connu par tout joueur et bien plus logique

2023-12-19 09:48 UTC, dadodasyra commented on objets/vote-key.md
> +Grâce à cette clé vous pouvez obtenir du stuff de moyenne qualité :
de moyenne qualité ?? serieusement ?

2023-12-19 09:48 UTC, dadodasyra commented on outils/grapnel.md
> +## Obtention
même remarque

2023-12-19 09:48 UTC, dadodasyra commented on outils/hammer.md
> +Lorsque le joueur casse un bloc, les blocs dans une zone de 3x3x2 autour du bloc cassé seront également détruits si jamais ils sont du même type que celui visé par le joueur.
c'est faux, c'est bel et bien 3x3x3 avec 1 de rayon par rapport au centre.

2023-12-19 09:48 UTC, dadodasyra commented on outils/histerite-hoe.md
> +## Obtention
même remarque

2023-12-19 09:48 UTC, dadodasyra commented on outils/histerite-shovel.md
> +Elle retire trois blocs de largeur et de longueur (1 bloc de rayon) autour du bloc visé.
là le 1 bloc de rayon est supprimable parce que pas vrai dans l'axe y

2023-12-19 09:48 UTC, dadodasyra commented on outils/histerite-shovel.md
> ++ La poudre de béton
https://minecraft.fandom.com/fr/wiki/B%C3%A9ton_en_poudre
ça s'appelle béton en poudre dans le jeu

2023-12-19 10:02 UTC, SwouitAzia commented on blocs/histerite-block.md
> +Le bloc en Histerite est le regroupement de 9 [lingots d'Histerite](https://histeria.fr/wiki/objets/histerite).
je me suis basé sur ce qui a été accepté sur la repository du pack, je change alors.

2023-12-19 10:07 UTC, SwouitAzia commented on blocs/reinforced-obsidian.md
> +Cette obsidienne est très pratique pour protéger vos bases grâce à sa résistance générale. Elle peut également être utilisée pour fabriquer le casseur à obsidienne.
l'hyperlink je l'ai déjà mis en haut

2023-12-19 10:09 UTC, SwouitAzia commented on boss/fonctionnement-des-boss.md
> +Le Colisée, accessible via la commande __/boss__ en jeu, vous permet d'accéder au lieu de combat contre les boss. Le PvP y est __désactivé__ mais __vous pouvez y perdre votre stuff__.
![image](https://github.com/HisteriaMC/histeria-wiki/assets/126331308/8645dadf-62d6-4af8-8ddc-27fd27bc2a99)

2023-12-19 10:10 UTC, SwouitAzia commented on boss/hermes.md
> +  - Les sandales d'Hermes possèdent l'enchantement unique [__Reset__](https://histeria.zelytra.fr/wiki/enchants/reset) qui permet, lorsqu'il est activé, de réinitialiser tout vos temps de recharge ac
tous vos oui, "tous" s'accorde avec les "temps de recharge"

2023-12-19 10:11 UTC, SwouitAzia commented on commandes/graded-commands.md
> +# Commandes gradés
commandes gradées... c'est les joueurs qui sont gradés pas les commandes.

2023-12-19 10:12 UTC, SwouitAzia commented on enchantements/shield.md
> +Quand le porteur est frappé, tout les dégâts du coup reçu s'annulent !
oui

2023-12-19 10:13 UTC, SwouitAzia commented on mondes/minage-servers.md
> +Il existe 4 serveurs minages sur Histeria, conçus pour permettre aux joueurs de trouver des minerais plus facilement. Ces serveurs sont également le seul endroit où vous pouvez trouver de l'[Histerit
je rectifie, pareil pour "serveurs factions" qui va passer à "serveurs faction".

2023-12-19 10:16 UTC, SwouitAzia commented on objets/histerite-key.md
> +| 1 [Eponge puissante](https://histeria.fr/wiki/objets/sponge) (à écrire)                                   | 3,51               |
aucune page sur l'éponge puissante (donc je peux pas insérer d'hyperlink)

2023-12-19 10:19 UTC, SwouitAzia commented on objets/kill-tag.md
> +Un Kill-Tag est un badge applicable sur votre épée grâce à [l'enclume en Histerite](https://histeria.fr/wiki/blocs/histerite-anvil). Il permet d'afficher un message personnalisé dans le chat lorsque
récompenses d'events = pour contenu limité donc pas assez pertinent je trouve (il faudra aussi l'écrire sur tous les autres items obtenables durant events)

2023-12-19 10:21 UTC, SwouitAzia commented on outils/histerite-shovel.md
> ++ La poudre de béton
les 2 marchent

2023-12-19 10:21 UTC, SwouitAzia commented on outils/histerite-shovel.md
> ++ La poudre de béton
je m'en suis rendu compte que maintenant

2023-12-19 10:36 UTC, SwouitAzia commented on blocs/histerite-block.md
> +Il est également très utilisé pour un grand nombre de crafts comme la [terre fertilisée](https://histeria.fr/wiki/blocs/fertilized-dirt), le coffre en Histerite, l'obsidienne renforcé et bien plus en
obsidienne renforcée il y en a une, coffre en histerite non.

2023-12-19 10:39 UTC, SwouitAzia commented on blocs/lucky-block.md
> +| punching ball |1.12|                     Fait apparaître une [Boule de frappe](https://histeria.fr/wiki/objets/punching-ball)                               |
tu l'as accepté sur la repository du pack

2023-12-19 12:23 UTC, SwouitAzia commented
je viens de mettre à jour

2023-12-19 20:27 UTC, dadodasyra commented
je vois 47 conversations unresolved, c'est tout ce que je vois, et sachant que ça m'a prit 1h à review je vais pas y repasser 1h si je suis pas sur que tout est fix

2024-01-09 17:57 UTC, ItamSurMc approved these changes

2024-01-09 18:00 UTC, ItamSurMc commented
@SwouitAzia il faut que tu résolves les conflits

2024-01-10 08:09 UTC, dadodasyra requested changes

2024-01-10 08:09 UTC, dadodasyra commented on objets/obsidian-breaker.md
>  %%name=Casseur d'obsidienne%%
consistance dans le nom et le titre

2024-01-10 08:09 UTC, dadodasyra commented on objets/seed-planter.md
> +Le planteur de graines est un objet permettant de planter des graines dans une zone de 3 x 3. Il permet également de récolter des [fruits de Nocturite](https://histeria.fr/wiki/objets/nocturite-fruit
tant qu'on y est ça pose les graines vanilla sur une ligne droite pour pasteque et pumpkin

2024-01-10 08:09 UTC, dadodasyra commented on boss/poseidon.md
> +  - Le trident légendaire de poséidon. Possède l'enchantement unique [__Tsunami__](https://histeria.zelytra.fr/wiki/enchants/tsunami), ayant le pouvoir de ralentir drastiquement vos adversaires de fa
changer ce lien de redirection

2024-01-10 18:45 UTC, ItamSurMc commented
@dadodasyra

2024-01-10 23:29 UTC, dadodasyra commented
Pas mal de brouillon dans le commit "update" faut que je review a nouveau tout. Le outdated et tout on peut pas le laisser. Autant mettre un joli message en mode cette page a été marquée comme non a jour ou jzp quoi. Pareil pourquoi 0 pv. Y a un lien de redirection vide aussi bref

2024-01-11 05:11 UTC, Tonmou8128 commented
> je compte faire une PR spécialement pour les boss parce que je peux pas tout faire sur une seule PR

Les boss je m'en occupe

2024-01-11 14:30 UTC, dadodasyra approved these changes
Ne pas oublier le dernier comm

2024-01-11 15:49 UTC, merged