Update du coffre d'arène
HisteriaMC/histeria-wiki pull request #233
Opened 2023-12-22 05:59 UTC by Tonmou8128

Encore des problèmes
Là j'ai patch 2 ou 3 hyperlinks mal mis, et enlevé le tiret principal, vu que les loots sont séparés distinctement maintenant.
Il y a toujours le problème sur le site

Fix #232

2023-12-27 12:08 UTC, Tonmou8128 commented
D'après le guide Markdown, j'ai pas mis de ligne vide avant les lignes alors qu'il fallait le faire, c'est fait maintenant

2024-01-09 17:55 UTC, ItamSurMc requested changes

2024-01-09 17:55 UTC, ItamSurMc commented on mondes/arena-chest.md
> +- 8 pommes en histerite
Mettre le lien de redirection vers la pomme en hist

2024-01-09 17:55 UTC, ItamSurMc commented on mondes/arena-chest.md
> +- 8 pommes en histerite
Mettre le lien de redirection vers la pomme en hist

2024-01-09 17:55 UTC, ItamSurMc commented on mondes/arena-chest.md
> +- 4 pommes en histerite
Mettre le lien de redirection vers la pomme en hist

2024-01-09 17:55 UTC, ItamSurMc commented on mondes/arena-chest.md
>      > Il y a 1 chance sur 8 pour que un livre enchanté contenant un enchantement d'arène, qui sont [Archéologie](https://histeria.fr/wiki/enchantements/archeologie), [Execution](https://histeria.fr/w
Mettre le lien de redirection vers le speed stick

2024-01-09 18:03 UTC, ItamSurMc commented
@Tonmou8128 je vois que tu viens de faire un commit. Donc, lorsque tu fais une tache demandée, tu cliques sur "Resolve conversation"

2024-01-09 18:04 UTC, Tonmou8128 commented
> @Tonmou8128 je vois que tu viens de faire un commit. Donc, lorsque tu fais une tache demandée, tu cliques sur "Resolve conversation"

C'est fait

2024-01-09 18:12 UTC, ItamSurMc approved these changes

2024-01-09 18:13 UTC, merged