Commande /settings
HisteriaMC/histeria-wiki pull request #235
Opened 2024-01-05 13:08 UTC by Tonmou8128

Fix #234 

Création de la page de la commande /settings que j'ai nommé commande de configuration ( titre du menu de /settings ).
Je suis preneur pour des améliorations, des changements ou des corrections.

2024-01-09 17:49 UTC, ItamSurMc commented on commandes/settings-command.md
> +La dernière configuration permet de choisir la couleur des particules de pots. Cette option n'est disponible que pour les joueurs gradés. Elle permet également de choisir les items qui seront filtrés
pots -> potions
items -> objets

2024-01-10 05:29 UTC, Tonmou8128 commented on commandes/settings-command.md
> +La commande **/settings** permet de configurer de nombreux paramètres afin de créer une expérience de jeu personnalisée. Le menu de configuration est également disponible avec le Paramettreur, qui es
Dans la PR #230, Nextag harmonise le wiki en français, donc mon avis est de laisser PNJ. Après si ça rend mal, je peux changer

2024-01-10 05:33 UTC, Tonmou8128 commented on commandes/settings-command.md
> +La commande **/settings** permet de configurer de nombreux paramètres afin de créer une expérience de jeu personnalisée. Le menu de configuration est également disponible avec le Paramettreur, qui es
Enfin même partout, comme les corrections demandées en dessous, mais NPC est anglais et PNJ français

2024-01-10 08:14 UTC, dadodasyra requested changes
Je suis pas convaincu de l'idée de tout expliquer prcq ça peut vite bouger et devenir outdated mais bon maintenant que c'est fait

2024-01-10 08:14 UTC, dadodasyra commented on commandes/settings-command.md
> +La catégorie des **Boxs** ne propose que deux options:
"que deux" c'est assez péjoratif

2024-01-10 08:14 UTC, dadodasyra commented on commandes/settings-command.md
> +La dernière configuration permet de choisir la couleur des particules de potions. Cette option n'est disponible que pour les [joueurs gradés](https://histeria.fr/wiki/commandes/graded-commands). Elle
aller à la ligne pour l'autre setting (filter drop)

2024-01-10 16:06 UTC, ItamSurMc approved these changes

2024-01-10 16:13 UTC, ItamSurMc commented
@dadodasyra

2024-01-10 17:14 UTC, dadodasyra approved these changes

2024-01-11 19:54 UTC, merged