Dossier récompenses
HisteriaMC/histeria-wiki pull request #260
Opened 2024-01-26 06:37 UTC by Tonmou8128

Fix #252 

Ajout du dossier récompenses avec les pages du calendrier de vote et des kits

2024-02-04 11:10 UTC, dadodasyra requested changes
+ le nom de dossier récompenses avec un accent risque pas de passer, @zelytra ?

2024-02-04 11:10 UTC, dadodasyra commented on récompenses/kits.md
Bof convaincu de la manière affiché.. C'est bof lisible. Et plus simple d'y accédeer in game, tu pourrais dire aussi qu'on peut voir le kit in game en preview

2024-02-04 11:10 UTC, dadodasyra commented on récompenses/vote-calendar.md
> +Voter pour le serveur est un bon moyen de nous soutenir. En le faisant, les joueurs peuvent obtenir un 9 [lingots d'Histerite](https://histeria.fr/wiki/objets/histerite), 10 [cobblestone compressée](
à reformuler la phrase ticket de loterie (et ça prend qu'un t) + quand les joueurs sont gradés ils en ont plus. Indiquez les probas aussi:
```php
        if ($player->hasPermission("vote.omega") || $player->hasPermission("vote.inter")) $execute = 3;
        else if ($player->hasPermission("vote.vip")) $execute = 2;

        if (mt_rand(0, 5) === 0) $ticket = CustomItems::LOTTERY_TICKET()->setCount($execute); //Give ticket de lotterie
        if (mt_rand(0, 5) === 0) $ticket = CustomItems::NOCTURITE_SEEDS()->setCount($execute);
```
mt_rand inclus les deux valeurs donc c'est 1 chance sur 6

2024-02-04 11:10 UTC, dadodasyra commented on récompenses/vote-calendar.md
> +%%name=Calendrier de vote%%
Le nom est bof inclusif, on parle aussi du vote sans parler du calendrier.. j'ai pas trop d'idée là

2024-02-04 11:10 UTC, dadodasyra commented on récompenses/vote-calendar.md
> +| 2 | Tout les [outils en Histerite](https://histeria.fr/wiki/outils) |
```suggestion
| 2 | Tous les [outils en Histerite](https://histeria.fr/wiki/outils) |
```

2024-02-04 11:10 UTC, dadodasyra commented on récompenses/vote-calendar.md
> +| 7 | 128 [cobblestone compressée](https://histeria.fr/wiki/objets/compressed-cobblestone) |
pluriel ?

2024-02-04 11:10 UTC, dadodasyra commented on récompenses/vote-calendar.md
> +| 33 | Fast learner (+1 niveau sur chaque métier) |
hyperlink jobs, (ça existe ?)

2024-02-04 11:35 UTC, Tonmou8128 commented on récompenses/vote-calendar.md
> +| 33 | Fast learner (+1 niveau sur chaque métier) |
Les jobs sont actuellement en état de draft PR

2024-02-04 11:35 UTC, Tonmou8128 commented on récompenses/vote-calendar.md
> +%%name=Calendrier de vote%%
Récompenses du vote ?

2024-02-04 11:38 UTC, Tonmou8128 commented on récompenses/vote-calendar.md
> +| 7 | 128 [cobblestone compressée](https://histeria.fr/wiki/objets/compressed-cobblestone) |
Cobblestones compressées ou cobblestone compressées ?

2024-02-04 12:35 UTC, dadodasyra commented on récompenses/vote-calendar.md
> +| 7 | 128 [cobblestone compressée](https://histeria.fr/wiki/objets/compressed-cobblestone) |
2eme

2024-02-04 12:35 UTC, dadodasyra commented on récompenses/vote-calendar.md
> +%%name=Calendrier de vote%%
oui ? + nom du fichier

2024-02-04 19:44 UTC, Tonmou8128 commented
Cette semaine j'aurai pas le temps, pas avant vendredi soir

2024-02-05 08:19 UTC, zelytra commented
> * le nom de dossier récompenses avec un accent risque pas de passer, @zelytra ?

Risqué car jamais testé, a voir

2024-02-10 14:28 UTC, Tonmou8128 commented
J'ai réglé tous les conflits

2024-02-10 15:27 UTC, Tonmou8128 commented
Fix #154

2024-02-15 21:17 UTC, dadodasyra approved these changes

2024-02-15 21:22 UTC, merged