Contrôle fiscal lottery ticket
HisteriaMC/histeria-wiki pull request #267
Opened 2024-02-26 14:57 UTC by Tonmou8128

Ajout d'un paragraphe manquant expliquant qu'il existe une chance de recevoir un contrôle fiscal

2024-02-27 15:51 UTC, dadodasyra requested changes

2024-02-27 15:51 UTC, dadodasyra commented on objets/lottery-ticket.md
> +Malheureusement, l'état s'en mêle parfois et lorsqu'un ticket est utilisé, il y a 5% de chance qu'un contrôle fiscal s'impose. Le montant d'argent qui était destiné est alors prélevé du compte du jou
40% de ?

2024-02-29 13:34 UTC, dadodasyra commented on objets/lottery-ticket.md
> +Malheureusement, l'état s'en mêle parfois et lorsqu'un ticket est utilisé, il y a 5% de chance qu'un contrôle fiscal s'impose. Le montant d'argent qui était destiné est alors prélevé du compte du jou
Bah en soit oui. Mais là tu dis 40% on sait pas si c'est 40% de la somme gagné, de l'argent qu'a le joueur

2024-02-29 14:37 UTC, Tonmou8128 commented on objets/lottery-ticket.md
> +Malheureusement, l'état s'en mêle parfois et lorsqu'un ticket est utilisé, il y a 5% de chance qu'un contrôle fiscal s'impose. Le montant d'argent qui était destiné est alors prélevé du compte du jou
C'est mieux ?

2024-02-29 16:49 UTC, dadodasyra approved these changes

2024-02-29 16:49 UTC, dadodasyra approved these changes

2024-03-02 15:32 UTC, merged