Nouvelles pages + corrections
HisteriaMC/histeria-wiki pull request #273
Opened 2024-04-05 13:49 UTC by Tonmou8128

Fix #270, Fix #259, Fix #251, Fix #242

## Nouvelles pages:
- Bloc néon
- Explorateur de coffre
- Brise-roche

## Correction de bugs:
- Lien invalide sur la page serveur faction § mdf
- Ajout d'une même icone pour les pages mdf et ap
- Correction du craft du drawer upgrade
- Ajout de la commande /paylumenn
- Meilleure mise en page de la page du coffre d'arène
- Suppression d'une ligne sur la page des commandes gradées, sûrement une faute de frappe
- Changement de la texture de la cobble compressée
- Meilleure mise en page pour la page des kits
- Le lien vote.histeria.fr sur la page des kits renvoyait vers https://histeria.fr/wiki/recompenses/vote.histeria.fr, je comprends pas donc j'ai remplacé par le lien de pocket servers

2024-04-05 20:41 UTC, dadodasyra requested changes

2024-04-05 20:41 UTC, dadodasyra commented on .assets/blocks/furnace.png
Devrait etre orienté vers la gauche

2024-04-05 20:41 UTC, dadodasyra commented on blocs/cobble-breaker.md
> +Les probabilités sont disonibles sur la page de la [cobblestone compressée](https://histeria.fr/wiki/objets/compressed-cobblestone).
```suggestion
Les probabilités sont disponibles sur la page de la [cobblestone compressée](https://histeria.fr/wiki/objets/compressed-cobblestone).
```

2024-04-05 20:41 UTC, dadodasyra commented on blocs/cobble-breaker.md
> +Le brise-roche est disponible aux **spawns de chaque serveur**, mais il peut également être construit.
bof une construction

2024-04-05 20:41 UTC, dadodasyra commented on blocs/neon.md
> +Le bloc néon est un bloc décoratif, et très joli ! Ce bloc animé alterne entre toutes les couleurs.
```suggestion
Le bloc néon est un bloc décoratif. Ce bloc animé alterne entre plusieurs couleurs. 
```

2024-04-05 20:41 UTC, dadodasyra commented on récompenses/kits.md
> +- **Vote**: Ce kit est disponible pour chaque joueur ayant [voté](https://minecraftpocket-servers.com/server/82450/vote/) le jour-même.
je refuse, on garde vote.histeria.fr

2024-04-05 20:41 UTC, dadodasyra commented on récompenses/kits.md
> -Le contenu de chaque kit peut être aperçu en jeu. Les kits peuvent être récupérés dans un coffre ou directement dans l'inventaire.
pourquoi ?

2024-04-06 07:10 UTC, Tonmou8128 commented on récompenses/kits.md
> +- **Vote**: Ce kit est disponible pour chaque joueur ayant [voté](https://minecraftpocket-servers.com/server/82450/vote/) le jour-même.
Ok, mais ça marchait pas avant

2024-04-06 07:16 UTC, Tonmou8128 commented on récompenses/kits.md
> -Le contenu de chaque kit peut être aperçu en jeu. Les kits peuvent être récupérés dans un coffre ou directement dans l'inventaire.
De quoi ? La phrase je l'ai déplacée vers plus haut, et j'ai rajouté 2 sous-titres car la page était juste un enorme pavé

2024-04-12 16:27 UTC, dadodasyra approved these changes

2024-04-13 12:58 UTC, Tonmou8128 commented
Tout est fait

2024-04-16 06:49 UTC, dadodasyra approved these changes

2024-04-29 08:54 UTC, merged