Ajout de la section boss
HisteriaMC/histeria-wiki pull request #3
Opened 2023-02-25 03:20 UTC by xnaveman

Section boss commencée, avec l'ajout de la description de arès et zeus nottamment, ainsi qu'une explication générale sur les boss. Ajout d'une catégorie boss et example-screenshots dans le .assets pour intégrer des images.

2023-02-25 12:16 UTC, zelytra requested changes
Demande de correctifs:
- Changer le nom de la catégorie `Boss` par `boss`. Pour rappel les dossier/fichier ne doivent jamais contenir de majuscule
- Pourquoi le nom de dossier `example-screenshots` ? Ce ne sont pas des exemples, changer le nom du dossier pour qu’il corresponde mieux a se qu'il contient

Autrement, tou est en ordre

2023-02-25 12:16 UTC, zelytra commented on Boss/zeus.md
> +  - Tranchant V
Pourquoi y mettre comme marker un `+` au lieu d'un `-` comme le premier ? C'est une sous liste elle devrais avoir ce format :
```
+ liste
 - sous liste
 - sous liste
```

2023-02-25 12:16 UTC, zelytra commented on worlds/faction2.md
> +# Le monde faction 2
Document vide, pourquoi l'ajouter ?

2023-02-25 12:16 UTC, zelytra commented on worlds/faction3.md
> +# Le monde faction 3
Document vide, pourquoi l'ajouter ?

2023-02-25 15:46 UTC, xnaveman commented
correctifs effectués. Les deux documents sur les mondes factions vides sont maintenant complétés.

2023-02-25 15:55 UTC, zelytra requested changes

2023-02-25 15:55 UTC, zelytra commented on Boss/explication générale.md
> +![colosseum](https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/example-screenshots/colosseum.png)
Le lien n'est pas bon

2023-02-25 15:55 UTC, zelytra commented on Boss/explication générale.md
> +##### (objets uniques référencés dans les pages des boss spécifiques)
Quel est ce balisage ? Un blockquote serais plus approprié (https://www.markdownguide.org/cheat-sheet/)

2023-02-25 15:55 UTC, zelytra commented on worlds/faction1.md
> +![gouffre](https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/boss/gouffre.png)
Cette image n'existe pas

2023-02-25 15:55 UTC, zelytra commented on worlds/faction1.md
> +![blackmarket](https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/boss/blackmarket.png)
Cette image n'existe pas

2023-02-25 15:55 UTC, zelytra commented on worlds/faction2.md
> +![faction2](https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/boss/faction2.png)
Mauvais lien

2023-02-25 15:55 UTC, zelytra commented on worlds/faction3.md
> +![faction3](https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/boss/faction3.png)
Mauvais lien

2023-02-25 15:55 UTC, zelytra commented on worlds/mondes-faction.md
> +![sortie](https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/boss/sortie.png)
Mauvais lien

2023-02-25 15:55 UTC, zelytra commented on worlds/mondes-faction.md
> +![jump](https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/boss/jump.png)
Mauvais lien

2023-02-25 16:07 UTC, xnaveman commented
Mauvais liens d'images corrigés, les anciens liens avant la modification du nom de dossier étaient toujours présents et sont maintenant bons, ainsi que les liens dans les fichiers des mondes factions qui n'étaient pas dirigés dans le bon dossier.

2023-02-25 16:12 UTC, zelytra requested changes
Le nom de la catégorie ne respecte toujours pas le format. Il ne dois pas y avoir de majuscule

2023-02-25 16:12 UTC, zelytra commented on worlds/faction1.md
> +![gouffre](https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/pictures/gouffre.png)
L'image n’existe toujours pas

2023-02-25 16:12 UTC, zelytra commented on Boss/explication générale.md
> +# Explication des Boss
Le nom du fichier ne respecte pas le format cf Good practice du wiki

2023-02-25 16:57 UTC, xnaveman commented on worlds/faction1.md
> +![gouffre](https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/pictures/gouffre.png)
image ajoutée

2023-02-25 17:09 UTC, zelytra approved these changes
Tout est bon coté syntax. En attente de @dadodasyra pour vérif du contenue

2023-02-25 17:30 UTC, dadodasyra approved these changes
En plus des nombreux commentaires, concernant les images : 
Le nom de l'image de sortie n'est pas assez explicite. (Sorties faction)
Peut être qu'au lieu de mettre boss pareil on peut mettre entité puis sous dossier boss. Ca permettrait de garder le black market dedans.
Le nom pictures me semble un peu trop générique mais j'avoue que j'ai pas masse autres idées

2023-02-25 17:30 UTC, dadodasyra commented on boss/explication-générale.md
> +Les boss peuvent apparaître en monde de __faction__. Leur temps avant d'apparaître varie en fonction du nombre de joueurs connectés, tournant généralement autour des 9H environ.
L'usage de serveur serait plus clair au lieu de monde.
"Tournant" fait pas méga pro. À reformuler avec un truc utilisant le terme moyenne.

2023-02-25 17:30 UTC, dadodasyra commented on boss/ares.md
> +#### __Points de Vie : 12 000__
Le fait que la donnée soit dans un titre et surtout du même formatage noie la valeur dans sa description.

2023-02-25 17:30 UTC, dadodasyra commented on boss/explication-générale.md
> +> A noter qu'une commande __+boss__ est disponible sur discord afin d'avoir un timer sur les prochaines apparitions de boss :
Rajouter un todo vers une page wiki concernant soit toutes les commandes discord soit catégories de commandes. Au moins le todo quoi

2023-02-25 17:30 UTC, dadodasyra commented on boss/explication-générale.md
> +> A noter qu'une commande __+boss__ est disponible sur discord afin d'avoir un timer sur les prochaines apparitions de boss :
Oué on peut ignorer ca en fait faudra juste que qqn le fasses un jour

2023-02-25 17:30 UTC, dadodasyra commented on boss/explication-générale.md
> ++ De l'argent, maximum ~50 000$ pour les premiers
Maximum environ. Y a t'il un vrai maximum ? Il faut préciser cette info en utilisant le code

2023-02-25 17:30 UTC, dadodasyra commented on worlds/faction1.md
> +## description
Pas de nom de catégorie sans majuscule

2023-02-25 17:30 UTC, dadodasyra commented on worlds/faction1.md
> +# Le monde faction 1
Encore une fois on préférera le terme serveur à monde

2023-02-25 17:30 UTC, dadodasyra commented on worlds/faction1.md
> +Le marché noir est un marché secret qui se déplace très souvent, il ne reste jamais au même endroit très longtemps. Il vous permetrra d'acheter des items rares, de désenchanter vos objets tout en réc
Rajouter le temps qu'il faut pour changer

2023-02-25 17:30 UTC, dadodasyra commented on worlds/faction2.md
> +Le monde de faction 2 est le deuxième monde faction disponible. Le build du spawn est axé sur le thème du japon, avec de nombreux cerisiers japonais, aisni que des temples et d'autres structures.
Pourquoi rajouter un de devant faction alors qu'avant non. Même remarque pour la description, voir fac1

2023-02-25 17:30 UTC, dadodasyra commented on worlds/faction3.md
> +Le monde faction 3 est le dernier serveur disponible en faction, et très souvent le moins visité par les joueurs. Le build du spawn est axé sur le thème du far west et de la ruée vers l'or, avec un t
Voir fac1

2023-02-25 17:30 UTC, dadodasyra commented on worlds/mondes-faction.md
> +Il existe 3 mondes de faction différents sur le serveur, simplement nommés faction 1, 2 et 3. Ces mondes sont les mondes les plus utilisés, puisque le __PvP y est activé__, et dispose d'arènes, de wa
Serveurs pas mondes

2023-02-25 17:30 UTC, dadodasyra commented on worlds/mondes-faction.md
> +Il existe 3 mondes de faction différents sur le serveur, simplement nommés faction 1, 2 et 3. Ces mondes sont les mondes les plus utilisés, puisque le __PvP y est activé__, et dispose d'arènes, de wa
+trop de répétition

2023-02-25 17:30 UTC, dadodasyra commented on worlds/mondes-faction.md
> +#### La map fait environ 12 500 x 12 500
On arrête les environ, les tailles sont définis et ne sont pas les mêmes sur tout les serveurs

2023-02-25 17:30 UTC, dadodasyra commented on worlds/mondes-faction.md
> +Les mondes factions disposent de sorties du lobby pour chaque direction. Une fois là bas, sneak pour sortir de la zone protégée et arriver en warzone. Vous pouvez ensuite accéder au reste de la map e
Pas un lobby puisque le lobby sert a rediriger les joueurs. Préférer spawn ou hub en 2eme solution

2023-02-25 17:30 UTC, dadodasyra commented on worlds/mondes-faction.md
> +Des parcours de jump ont été construit un peu partout dans chaque monde faction. Idéal pour patienter ou simplement pour vous entraîner au parcours.
Idéal pour patienter ? Really ? Passer le temps plutôt en vrai. Prcq t'es pas sensé patienter sur hist

2023-02-25 17:30 UTC, dadodasyra commented on worlds/mondes-faction.md
> +Des parcours de jump ont été construit un peu partout dans chaque monde faction. Idéal pour patienter ou simplement pour vous entraîner au parcours.
Ce serait un aveux de faiblesse

2023-02-25 17:31 UTC, dadodasyra commented
Je me suis fail c'est un request change pas un approove

2023-02-26 01:04 UTC, xnaveman commented on boss/explication-générale.md
> +Les boss peuvent apparaître en monde de __faction__. Leur temps avant d'apparaître varie en fonction du nombre de joueurs connectés, tournant généralement autour des 9H environ.
phrase corrigée

2023-02-26 01:05 UTC, xnaveman commented on boss/ares.md
> +#### __Points de Vie : 12 000__
Donnée séparée du titre, maintenant plus claire et visible

2023-02-26 01:10 UTC, xnaveman commented on boss/explication-générale.md
> +> A noter qu'une commande __+boss__ est disponible sur discord afin d'avoir un timer sur les prochaines apparitions de boss :
ignoré

2023-02-26 01:12 UTC, xnaveman commented on worlds/faction1.md
> +## description
corrigé

2023-02-26 01:14 UTC, xnaveman commented on worlds/faction1.md
> +# Le monde faction 1
corrigé pour les 3 serveurs faction

2023-02-26 02:36 UTC, xnaveman commented
Toutes les corrections demandées ont normalement été faites. Le dossier boss passe désormais dans entities>boss comme demandé.

2023-02-26 10:55 UTC, zelytra requested changes
Je ne sais pas pourquoi cette modification a été faite. Mais pour les documents, les sous dossier sont interdis. il faut rollback la change

2023-02-26 11:40 UTC, dadodasyra commented
> Je ne sais pas pourquoi cette modification a été faite. Mais pour les documents, les sous dossier sont interdis. il faut rollback la change

Nan mais un sous dossier d'image c'est pas interdit nan ?

2023-02-26 11:50 UTC, zelytra commented
> > Je ne sais pas pourquoi cette modification a été faite. Mais pour les documents, les sous dossier sont interdis. il faut rollback la change
> 
> Nan mais un sous dossier d'image c'est pas interdit nan ?

Dans les assets c'est bon mais actuellement il l'as fais sur les documents

2023-02-26 12:32 UTC, xnaveman commented
j'ai mal compris la demande, my bad je refait ça.

2023-02-26 12:58 UTC, dadodasyra requested changes
Il manque aussi:

- [ ] Item dans la main de chaque boss, cf https://pastebin.com/5EXbt8Jw
- [ ] taille de chaque map des servs fac sur leur doc respective

1. Fac 1: 12500
2. Fac 2: 10000
3. Fac 3: 12500

2023-02-26 12:58 UTC, dadodasyra commented on entities/boss/explication-générale.md
> +Les boss peuvent apparaître dans les 3 serveurs __faction__. Leur temps avant d'apparaître varie en fonction du nombre de joueurs connectés, ce temps est en moyenne de 9h environ.
Si c'est une moyenne y a pas besoin d'environ à la fin. Pour préciser voici le code correspondant à la détermination du temps en seconde avant le respawn:
`self::$nextRespawn = time() + max(6 * $respawnDelay - ($players * (5 * $respawnDelay) - $respawnDelay) / 80, $respawnDelay);`
où $respawnDelay est 3600 défini par la config mais ne devrait pas changer, $players le nombre de joueur connecté sur le serveur faction en question. Ce lien peut être partagé sur le wiki https://www.desmos.com/calculator/bcfboks5o8?lang=fr il contient la formule mathématique propre associé au respawn où x c'est le nombre de joueurs et R la constante 3600. La temps le plus court par conséquent est 3600 (d'ou l'usage du max) ce qui arrive si il y a 83 joueurs ou plus connecté au faction.

2023-02-26 12:58 UTC, dadodasyra commented on entities/boss/explication-générale.md
> +Le colisée, accessible via la commande __/boss__ en jeu, vous permet d'accéder au lieu de combat contre les boss. Le PvP y est __désactivé__ mais __pas la perte de stuff__.
```suggestion
Le colisée, accessible via la commande __/boss__ en jeu, vous permet d'accéder au lieu de combat contre les boss. Le PvP y est __désactivé__ mais __vous pouvez y perdre votre stuff__. 
```

2023-02-26 12:58 UTC, dadodasyra commented on entities/boss/explication-générale.md
> +Le combat dure jusqu'à ce que le boss descende à __0 points de vie__.
Pas clair, dire ça après le statut de combat logger qui n'était déjà pas très clair induit en erreur, le joueur peut quitter le combat si il s'éloigne et attend le temps nécessaire comme en PvP.

2023-02-26 12:58 UTC, dadodasyra commented on entities/boss/explication-générale.md
> +    - jusqu'à ````~50 000$```` pour les premiers
```php
    public function getMoneyFromDamage($damage, $rank) : float|int
    {
        if($rank <= 2) $baseModifier = mt_rand(18, 20)/10;
        else $baseModifier = mt_rand(45, 50)/100;
        return ((45000 + $damage) * $baseModifier) / 2;
    }

    public function getLumennFromDamage($damage, $rank) : float|int
    {
        if($rank <= 2) $baseModifier = mt_rand(18, 20)/10;
        else $baseModifier = mt_rand(45, 50)/100;
        return (450 + ($damage/100)) * $baseModifier;
    }

    public function getForgeNoteNumberFromDamage($damage, $rank) : float|int
    {
        if($rank <= 2) $num = mt_rand(2, 4);
        else $num = 1;
        if($damage > 2500) $num += 1;
        return $num;
    }
```
Voici le code associé aux rewards, $damage étant le nombre de demi coeur et rank son classement.

2023-02-26 12:58 UTC, dadodasyra commented on entities/boss/explication-générale.md
> +seuls les joueurs ayant infligé __plus de 100 dégâts au boss__ recoivent les récompenses suivantes :
250 dégats en réalité, vérifié avec le code.
```suggestion
seuls les joueurs ayant infligé __plus de 250 dégâts au boss__ recoivent les récompenses suivantes :
```

2023-02-26 12:58 UTC, dadodasyra commented on entities/boss/explication-générale.md
> +
Parler quelque part du fait que le nombre de kill de boss et de dégats infligés sont sauvegardés et visible à l'entrée de l'arène.

2023-02-26 12:58 UTC, dadodasyra commented on entities/boss/poseidon.md
> ++ De l'argent selon votre position dans le classement des dégâts
Redire les récompenses à chaque boss est inutile puisqu'elles sont communes à chacun d'entre eux

2023-02-26 12:58 UTC, dadodasyra commented on worlds/serveurs-faction.md
> +     Pour y accéder : /arene
je pense qu'utiliser un > serait plus adéquat pour un texte aussi "peu important"

2023-02-26 16:51 UTC, dadodasyra requested changes
Même remarque dans faction2 & 3 que dans le faction1

2023-02-26 16:51 UTC, dadodasyra commented on worlds/faction1.md
> ++ 12 500 x 12 500
pas de phrase ??? en plus en soit c'est pas 12500 x 12500 mais le double, 12500 et -12500 étant la limite

2023-02-26 17:18 UTC, zelytra requested changes

2023-02-26 17:18 UTC, zelytra commented on boss/ares.md
> +![ares](https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/boss/ares.png)
Le lien n'est plus bon

2023-02-26 17:18 UTC, zelytra commented on boss/hermes.md
> +![hermes](https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/boss/hermes.png)
Le lien n'est plus bon

2023-02-26 17:18 UTC, zelytra commented on boss/zeus.md
> +![zeus](https://raw.githubusercontent.com/HisteriaMC/histeria-wiki/main/.assets/boss/zeus.png)
Le lien n'est plus bon

2023-03-01 16:35 UTC, xnaveman commented on entities/boss/explication-générale.md
> +Les boss peuvent apparaître dans les 3 serveurs __faction__. Leur temps avant d'apparaître varie en fonction du nombre de joueurs connectés, ce temps est en moyenne de 9h environ.
je n'arrive pas a bien comprendre la fonction en détail. j'ai certainement omis un truc mais d'après le graphique le temps de respawn minimal serait de 21654 secondes soit 6h. sauf que c'est rarement 6h max le temps de respawn.

2023-03-01 16:39 UTC, dadodasyra commented on entities/boss/explication-générale.md
> +Les boss peuvent apparaître dans les 3 serveurs __faction__. Leur temps avant d'apparaître varie en fonction du nombre de joueurs connectés, ce temps est en moyenne de 9h environ.
"le temps le plus court"

2023-03-01 16:45 UTC, dadodasyra commented on entities/boss/explication-générale.md
> +Les boss peuvent apparaître dans les 3 serveurs __faction__. Leur temps avant d'apparaître varie en fonction du nombre de joueurs connectés, ce temps est en moyenne de 9h environ.
Bien vu, en fait la constante 3600 a été modif à 7200 entre temps, je vais le modif sur le desmos

2023-03-01 16:46 UTC, dadodasyra commented on entities/boss/explication-générale.md
> +Les boss peuvent apparaître dans les 3 serveurs __faction__. Leur temps avant d'apparaître varie en fonction du nombre de joueurs connectés, ce temps est en moyenne de 9h environ.
Donc mini 7200sec et max le double de ce que tu avais dit

2023-03-02 19:57 UTC, xnaveman commented on entities/boss/explication-générale.md
> +Les boss peuvent apparaître dans les 3 serveurs __faction__. Leur temps avant d'apparaître varie en fonction du nombre de joueurs connectés, ce temps est en moyenne de 9h environ.
c'est fait, si jamais tu as le temps faudra juste pas oublier de mettre a jour le desmos.

2023-03-02 20:45 UTC, xnaveman commented on entities/boss/explication-générale.md
> +Les boss peuvent apparaître dans les 3 serveurs __faction__. Leur temps avant d'apparaître varie en fonction du nombre de joueurs connectés, ce temps est en moyenne de 9h environ.
changement fait, merci

2023-03-02 22:49 UTC, zelytra approved these changes
Tout est bon en attente de dado

2023-03-02 22:58 UTC, dadodasyra requested changes
3 derniers changements

2023-03-02 22:58 UTC, dadodasyra commented on worlds/faction1.md
> ++ 25 000 blocs de __hauteur__ et de __largeur__ (-12 500 à 12 500)
```suggestion
En faction 1 la map fait 25 000 blocks de rayon soit des coordonnées x et z -12 500 à 12 500.
```

2023-03-02 22:58 UTC, dadodasyra commented on worlds/faction2.md
> ++ 20 000 blocs de __hauteur__ et de __largeur__ (-10 000 à 10 000)
```suggestion
En faction 2 la map fait 20 000 blocks de rayon soit des coordonnées x et z -10 000 à 10 000.
```

2023-03-02 22:58 UTC, dadodasyra commented on worlds/faction3.md
> ++ 25 000 blocs de __hauteur__ et de __largeur__ (-12 500 à 12 500)
```suggestion
En faction 3 la map fait 25 000 blocks de rayon soit des coordonnées x et z -12 500 à 12 500.
```

2023-03-02 23:00 UTC, dadodasyra commented
Par contre comme écrit tout en bas de la page il reste 7 conversations en tout à résoudre, des anciennes reviews n'ont pas été lus/n'ont pas eu de modifications adéquates.

2023-03-02 23:58 UTC, xnaveman commented
l'explication générale a bien été corrigée en incluant bien plus de précisions sur les chiffres donnés

2023-03-03 19:31 UTC, dadodasyra approved these changes

2023-03-03 19:36 UTC, merged