Modif des {}et <> et []
HisteriaMC/histeria-wiki pull request #7
Opened 2023-02-26 17:42 UTC by CercleTour

Modif des {}et <> et []

2023-02-26 18:00 UTC, zelytra commented
Il faut synchronisé ton fork et commit de nouveau

2023-02-26 19:54 UTC, dadodasyra commented
ta tentative de merge a mal géré les conflits et on se retrouve avec du texte de résolution de conflit directement dans les fichiers

2023-02-27 20:47 UTC, dadodasyra requested changes

2023-02-27 20:47 UTC, dadodasyra commented on commands/faction-commandes.md
> +\<args\> = Argument obligatoir.
```suggestion
\<args\> = Argument obligatoire.
```

2023-02-27 20:47 UTC, dadodasyra commented on commands/faction-commandes.md
> +| `/f leader <player>` |  Mettre le rôle de chef a un joueur |
```suggestion
| `/f leader <player>` | Mettre le rôle de chef a un joueur |
```

2023-02-27 20:47 UTC, dadodasyra commented on commands/faction-commandes.md
> +| `/f money` |  Affiche la monnaie de faction |
```suggestion
| `/f money` | Affiche la monnaie de faction |
```

2023-02-28 10:17 UTC, dadodasyra approved these changes

2023-02-28 10:18 UTC, dadodasyra commented
@zelytra je peux pas merge sans ta review

2023-02-28 10:58 UTC, zelytra approved these changes

2023-02-28 10:58 UTC, merged